import { DSASheetType } from "./dsa-sheet-type";

const DSA_POWERSET: DSASheetType[] = [
  {
    topicId: "15",
    topicName: "Advanced Arrays & Strings",
    topicDescription: "Advanced problems related to arrays and strings.",
    problems: [
      {
        id: "91",
        name: "Sliding Window Maximum",
        description: "",
        link: "https://leetcode.com/problems/sliding-window-maximum/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [15],
      },
      {
        id: "92",
        name: "Minimum Window Substring",
        description: "",
        link: "https://leetcode.com/problems/minimum-window-substring/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [15],
      },
      {
        id: "93",
        name: "Longest Substring Without Repeating Characters",
        description: "",
        link: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [15],
      },
      {
        id: "94",
        name: "Substring with Concatenation of All Words",
        description: "",
        link: "https://leetcode.com/problems/substring-with-concatenation-of-all-words/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [15],
      },
      {
        id: "95",
        name: "Trapping Rain Water",
        description: "",
        link: "https://leetcode.com/problems/trapping-rain-water/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [15],
      },
      {
        id: "96",
        name: "Maximum Product Subarray",
        description: "",
        link: "https://leetcode.com/problems/maximum-product-subarray/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [15],
      },
    ],
  },
  {
    topicId: "16",
    topicName: "Advanced Sorting & Searching",
    topicDescription:
      "Advanced problems related to sorting and searching algorithms.",
    problems: [
      {
        id: "97",
        name: "Find Median in a Stream",
        description: "",
        link: "https://leetcode.com/problems/find-median-from-data-stream/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [16],
      },
      {
        id: "98",
        name: "Kth Largest Element in an Array",
        description: "",
        link: "https://leetcode.com/problems/kth-largest-element-in-an-array/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [16],
      },
      {
        id: "99",
        name: "Search in a Rotated Sorted Array",
        description: "",
        link: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [16],
      },
      {
        id: "100",
        name: "Find Peak Element",
        description: "",
        link: "https://leetcode.com/problems/find-peak-element/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [16],
      },
      {
        id: "101",
        name: "Median of Two Sorted Arrays",
        description: "",
        link: "https://leetcode.com/problems/median-of-two-sorted-arrays/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [16],
      },
      {
        id: "102",
        name: "Count of Smaller Numbers After Self",
        description: "",
        link: "https://leetcode.com/problems/count-of-smaller-numbers-after-self/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [16],
      },
    ],
  },
  {
    topicId: "17",
    topicName: "Advanced Linked List",
    topicDescription: "Advanced problems related to linked lists.",
    problems: [
      {
        id: "103",
        name: "Merge K Sorted Lists",
        description: "",
        link: "https://leetcode.com/problems/merge-k-sorted-lists/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [17],
      },
      {
        id: "104",
        name: "LRU Cache",
        description: "",
        link: "https://leetcode.com/problems/lru-cache/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [17],
      },
      {
        id: "105",
        name: "Flatten a Multilevel Doubly Linked List",
        description: "",
        link: "https://leetcode.com/problems/flatten-a-multilevel-doubly-linked-list/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [17],
      },
      {
        id: "106",
        name: "Copy List with Random Pointer",
        description: "",
        link: "https://leetcode.com/problems/copy-list-with-random-pointer/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [17],
      },
      {
        id: "107",
        name: "Reverse Nodes in k-Group",
        description: "",
        link: "https://leetcode.com/problems/reverse-nodes-in-k-group/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [17],
      },
      {
        id: "108",
        name: "Rotate List",
        description: "",
        link: "https://leetcode.com/problems/rotate-list/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [17],
      },
    ],
  },
  {
    topicId: "18",
    topicName: "Advanced Stacks & Queues",
    topicDescription: "Advanced problems related to stacks and queues.",
    problems: [
      {
        id: "109",
        name: "Largest Rectangle in Histogram",
        description: "",
        link: "https://leetcode.com/problems/largest-rectangle-in-histogram/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [18],
      },
      {
        id: "110",
        name: "Maximal Rectangle",
        description: "",
        link: "https://leetcode.com/problems/maximal-rectangle/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [18],
      },
      {
        id: "111",
        name: "Sliding Window Maximum",
        description: "",
        link: "https://leetcode.com/problems/sliding-window-maximum/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [18],
      },
      {
        id: "112",
        name: "Simplify Path",
        description: "",
        link: "https://leetcode.com/problems/simplify-path/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [18],
      },
      {
        id: "113",
        name: "Asteroid Collision",
        description: "",
        link: "https://leetcode.com/problems/asteroid-collision/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [18],
      },
      {
        id: "114",
        name: "Remove K Digits",
        description: "",
        link: "https://leetcode.com/problems/remove-k-digits/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [18],
      },
    ],
  },
  {
    topicId: "19",
    topicName: "Advanced Trees & Binary Search Trees",
    topicDescription:
      "Advanced problems related to trees and binary search trees.",
    problems: [
      {
        id: "115",
        name: "Binary Tree Maximum Path Sum",
        description: "",
        link: "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [19],
      },
      {
        id: "116",
        name: "Recover Binary Search Tree",
        description: "",
        link: "https://leetcode.com/problems/recover-binary-search-tree/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [19],
      },
      {
        id: "117",
        name: "Serialize and Deserialize Binary Tree",
        description: "",
        link: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [19],
      },
      {
        id: "118",
        name: "Binary Tree Zigzag Level Order Traversal",
        description: "",
        link: "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [19],
      },
      {
        id: "119",
        name: "Unique Binary Search Trees",
        description: "",
        link: "https://leetcode.com/problems/unique-binary-search-trees/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [19],
      },
      {
        id: "120",
        name: "Construct Binary Tree from Inorder and Postorder Traversal",
        description: "",
        link: "https://leetcode.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [19],
      },
    ],
  },
  {
    topicId: "20",
    topicName: "Advanced Graphs & Shortest Paths",
    topicDescription: "Advanced problems related to graphs and shortest paths.",
    problems: [
      {
        id: "121",
        name: "Minimum Number of Swaps to Make the Binary String Alternating",
        description: "",
        link: "https://leetcode.com/problems/minimum-number-of-swaps-to-make-the-binary-string-alternating/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [20],
      },
      {
        id: "122",
        name: "Word Ladder",
        description: "",
        link: "https://leetcode.com/problems/word-ladder/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [20],
      },
      {
        id: "123",
        name: "Swim in Rising Water",
        description: "",
        link: "https://leetcode.com/problems/swim-in-rising-water/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [20],
      },
      {
        id: "124",
        name: "Network Delay Time",
        description: "",
        link: "https://leetcode.com/problems/network-delay-time/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [20],
      },
      {
        id: "125",
        name: "Find the City With the Smallest Number of Neighbors",
        description: "",
        link: "https://leetcode.com/problems/find-the-city-with-the-smallest-number-of-neighbors/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [20],
      },
      {
        id: "126",
        name: "Dijkstra's Algorithm Implementation",
        description: "",
        link: "https://leetcode.com/problems/path-with-minimum-effort/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [20],
      },
    ],
  },
  {
    topicId: "21",
    topicName: "Advanced Dynamic Programming",
    topicDescription: "Advanced problems related to dynamic programming.",
    problems: [
      {
        id: "127",
        name: "Russian Doll Envelopes",
        description: "",
        link: "https://leetcode.com/problems/russian-doll-envelopes/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [21],
      },
      {
        id: "128",
        name: "Perfect Squares",
        description: "",
        link: "https://leetcode.com/problems/perfect-squares/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [21],
      },
      {
        id: "129",
        name: "Dungeon Game",
        description: "",
        link: "https://leetcode.com/problems/dungeon-game/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [21],
      },
      {
        id: "130",
        name: "Edit Distance",
        description: "",
        link: "https://leetcode.com/problems/edit-distance/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [21],
      },
      {
        id: "131",
        name: "Longest Increasing Path in a Matrix",
        description: "",
        link: "https://leetcode.com/problems/longest-increasing-path-in-a-matrix/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [21],
      },
      {
        id: "132",
        name: "Super Egg Drop",
        description: "",
        link: "https://leetcode.com/problems/super-egg-drop/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [21],
      },
    ],
  },
  {
    topicId: "22",
    topicName: "Tries & String Matching",
    topicDescription:
      "Problems related to tries and string matching algorithms.",
    problems: [
      {
        id: "133",
        name: "Design Add and Search Words Data Structure",
        description: "",
        link: "https://leetcode.com/problems/design-add-and-search-words-data-structure/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [22],
      },
      {
        id: "134",
        name: "Concatenated Words",
        description: "",
        link: "https://leetcode.com/problems/concatenated-words/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [22],
      },
      {
        id: "135",
        name: "Suffix Trie Implementation",
        description: "",
        link: "https://leetcode.com/problems/longest-duplicate-substring/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [22],
      },
      {
        id: "136",
        name: "KMP Algorithm - Pattern Matching",
        description: "",
        link: "https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [22],
      },
      {
        id: "137",
        name: "Aho-Corasick Algorithm",
        description: "",
        link: "https://leetcode.com/problems/multi-pattern-search/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [22],
      },
      {
        id: "138",
        name: "Minimum Unique Word Abbreviation",
        description: "",
        link: "https://leetcode.com/problems/minimum-unique-word-abbreviation/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [22],
      },
    ],
  },
  {
    topicId: "23",
    topicName: "Bit Manipulation & Number Theory",
    topicDescription:
      "Advanced problems related to bit manipulation and number theory.",
    problems: [
      {
        id: "139",
        name: "Single Number II",
        description: "",
        link: "https://leetcode.com/problems/single-number-ii/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [23],
      },
      {
        id: "140",
        name: "Gray Code",
        description: "",
        link: "https://leetcode.com/problems/gray-code/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [23],
      },
      {
        id: "141",
        name: "Maximum XOR of Two Numbers in an Array",
        description: "",
        link: "https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [23],
      },
      {
        id: "142",
        name: "Power of Four",
        description: "",
        link: "https://leetcode.com/problems/power-of-four/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [23],
      },
      {
        id: "143",
        name: "Number of 1 Bits",
        description: "",
        link: "https://leetcode.com/problems/number-of-1-bits/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [23],
      },
      {
        id: "144",
        name: "Sum of Two Integers (Without using + or -)",
        description: "",
        link: "https://leetcode.com/problems/sum-of-two-integers/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [23],
      },
    ],
  },
  {
    topicId: "15",
    topicName: "Advanced Arrays & Strings",
    topicDescription: "Advanced problems related to arrays and strings.",
    problems: [
      {
        id: "91",
        name: "Sliding Window Maximum",
        description: "",
        link: "https://leetcode.com/problems/sliding-window-maximum/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [15],
      },
      {
        id: "92",
        name: "Minimum Window Substring",
        description: "",
        link: "https://leetcode.com/problems/minimum-window-substring/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [15],
      },
      {
        id: "93",
        name: "Longest Substring Without Repeating Characters",
        description: "",
        link: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [15],
      },
      {
        id: "94",
        name: "Substring with Concatenation of All Words",
        description: "",
        link: "https://leetcode.com/problems/substring-with-concatenation-of-all-words/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [15],
      },
      {
        id: "95",
        name: "Trapping Rain Water",
        description: "",
        link: "https://leetcode.com/problems/trapping-rain-water/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [15],
      },
      {
        id: "96",
        name: "Maximum Product Subarray",
        description: "",
        link: "https://leetcode.com/problems/maximum-product-subarray/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [15],
      },
    ],
  },
  {
    topicId: "16",
    topicName: "Advanced Sorting & Searching",
    topicDescription:
      "Advanced problems related to sorting and searching algorithms.",
    problems: [
      {
        id: "97",
        name: "Find Median in a Stream",
        description: "",
        link: "https://leetcode.com/problems/find-median-from-data-stream/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [16],
      },
      {
        id: "98",
        name: "Kth Largest Element in an Array",
        description: "",
        link: "https://leetcode.com/problems/kth-largest-element-in-an-array/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [16],
      },
      {
        id: "99",
        name: "Search in a Rotated Sorted Array",
        description: "",
        link: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [16],
      },
      {
        id: "100",
        name: "Find Peak Element",
        description: "",
        link: "https://leetcode.com/problems/find-peak-element/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [16],
      },
      {
        id: "101",
        name: "Median of Two Sorted Arrays",
        description: "",
        link: "https://leetcode.com/problems/median-of-two-sorted-arrays/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [16],
      },
      {
        id: "102",
        name: "Count of Smaller Numbers After Self",
        description: "",
        link: "https://leetcode.com/problems/count-of-smaller-numbers-after-self/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [16],
      },
    ],
  },
  {
    topicId: "17",
    topicName: "Advanced Linked List",
    topicDescription: "Advanced problems related to linked lists.",
    problems: [
      {
        id: "103",
        name: "Merge K Sorted Lists",
        description: "",
        link: "https://leetcode.com/problems/merge-k-sorted-lists/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [17],
      },
      {
        id: "104",
        name: "LRU Cache",
        description: "",
        link: "https://leetcode.com/problems/lru-cache/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [17],
      },
      {
        id: "105",
        name: "Flatten a Multilevel Doubly Linked List",
        description: "",
        link: "https://leetcode.com/problems/flatten-a-multilevel-doubly-linked-list/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [17],
      },
      {
        id: "106",
        name: "Copy List with Random Pointer",
        description: "",
        link: "https://leetcode.com/problems/copy-list-with-random-pointer/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [17],
      },
      {
        id: "107",
        name: "Reverse Nodes in k-Group",
        description: "",
        link: "https://leetcode.com/problems/reverse-nodes-in-k-group/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [17],
      },
      {
        id: "108",
        name: "Rotate List",
        description: "",
        link: "https://leetcode.com/problems/rotate-list/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [17],
      },
    ],
  },
  {
    topicId: "18",
    topicName: "Advanced Stacks & Queues",
    topicDescription: "Advanced problems related to stacks and queues.",
    problems: [
      {
        id: "109",
        name: "Largest Rectangle in Histogram",
        description: "",
        link: "https://leetcode.com/problems/largest-rectangle-in-histogram/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [18],
      },
      {
        id: "110",
        name: "Maximal Rectangle",
        description: "",
        link: "https://leetcode.com/problems/maximal-rectangle/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [18],
      },
      {
        id: "111",
        name: "Sliding Window Maximum",
        description: "",
        link: "https://leetcode.com/problems/sliding-window-maximum/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [18],
      },
      {
        id: "112",
        name: "Simplify Path",
        description: "",
        link: "https://leetcode.com/problems/simplify-path/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [18],
      },
      {
        id: "113",
        name: "Asteroid Collision",
        description: "",
        link: "https://leetcode.com/problems/asteroid-collision/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [18],
      },
      {
        id: "114",
        name: "Remove K Digits",
        description: "",
        link: "https://leetcode.com/problems/remove-k-digits/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [18],
      },
    ],
  },
  {
    topicId: "19",
    topicName: "Advanced Trees & Binary Search Trees",
    topicDescription:
      "Advanced problems related to trees and binary search trees.",
    problems: [
      {
        id: "115",
        name: "Binary Tree Maximum Path Sum",
        description: "",
        link: "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [19],
      },
      {
        id: "116",
        name: "Recover Binary Search Tree",
        description: "",
        link: "https://leetcode.com/problems/recover-binary-search-tree/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [19],
      },
      {
        id: "117",
        name: "Serialize and Deserialize Binary Tree",
        description: "",
        link: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [19],
      },
      {
        id: "118",
        name: "Binary Tree Zigzag Level Order Traversal",
        description: "",
        link: "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [19],
      },
      {
        id: "119",
        name: "Unique Binary Search Trees",
        description: "",
        link: "https://leetcode.com/problems/unique-binary-search-trees/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [19],
      },
      {
        id: "120",
        name: "Construct Binary Tree from Inorder and Postorder Traversal",
        description: "",
        link: "https://leetcode.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [19],
      },
    ],
  },
  {
    topicId: "20",
    topicName: "Advanced Graphs & Shortest Paths",
    topicDescription: "Advanced problems related to graphs and shortest paths.",
    problems: [
      {
        id: "121",
        name: "Minimum Number of Swaps to Make the Binary String Alternating",
        description: "",
        link: "https://leetcode.com/problems/minimum-number-of-swaps-to-make-the-binary-string-alternating/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [20],
      },
      {
        id: "122",
        name: "Word Ladder",
        description: "",
        link: "https://leetcode.com/problems/word-ladder/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [20],
      },
      {
        id: "123",
        name: "Swim in Rising Water",
        description: "",
        link: "https://leetcode.com/problems/swim-in-rising-water/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [20],
      },
      {
        id: "124",
        name: "Network Delay Time",
        description: "",
        link: "https://leetcode.com/problems/network-delay-time/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [20],
      },
      {
        id: "125",
        name: "Find the City With the Smallest Number of Neighbors",
        description: "",
        link: "https://leetcode.com/problems/find-the-city-with-the-smallest-number-of-neighbors/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [20],
      },
      {
        id: "126",
        name: "Dijkstra's Algorithm Implementation",
        description: "",
        link: "https://leetcode.com/problems/path-with-minimum-effort/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [20],
      },
    ],
  },
  {
    topicId: "21",
    topicName: "Advanced Dynamic Programming",
    topicDescription: "Advanced problems related to dynamic programming.",
    problems: [
      {
        id: "127",
        name: "Russian Doll Envelopes",
        description: "",
        link: "https://leetcode.com/problems/russian-doll-envelopes/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [21],
      },
      {
        id: "128",
        name: "Perfect Squares",
        description: "",
        link: "https://leetcode.com/problems/perfect-squares/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [21],
      },
      {
        id: "129",
        name: "Dungeon Game",
        description: "",
        link: "https://leetcode.com/problems/dungeon-game/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [21],
      },
      {
        id: "130",
        name: "Edit Distance",
        description: "",
        link: "https://leetcode.com/problems/edit-distance/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [21],
      },
      {
        id: "131",
        name: "Longest Increasing Path in a Matrix",
        description: "",
        link: "https://leetcode.com/problems/longest-increasing-path-in-a-matrix/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [21],
      },
      {
        id: "132",
        name: "Super Egg Drop",
        description: "",
        link: "https://leetcode.com/problems/super-egg-drop/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [21],
      },
    ],
  },
  {
    topicId: "22",
    topicName: "Tries & String Matching",
    topicDescription:
      "Problems related to tries and string matching algorithms.",
    problems: [
      {
        id: "133",
        name: "Design Add and Search Words Data Structure",
        description: "",
        link: "https://leetcode.com/problems/design-add-and-search-words-data-structure/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [22],
      },
      {
        id: "134",
        name: "Concatenated Words",
        description: "",
        link: "https://leetcode.com/problems/concatenated-words/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [22],
      },
      {
        id: "135",
        name: "Suffix Trie Implementation",
        description: "",
        link: "https://leetcode.com/problems/longest-duplicate-substring/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [22],
      },
      {
        id: "136",
        name: "KMP Algorithm - Pattern Matching",
        description: "",
        link: "https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [22],
      },
      {
        id: "137",
        name: "Aho-Corasick Algorithm",
        description: "",
        link: "https://leetcode.com/problems/multi-pattern-search/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [22],
      },
      {
        id: "138",
        name: "Minimum Unique Word Abbreviation",
        description: "",
        link: "https://leetcode.com/problems/minimum-unique-word-abbreviation/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [22],
      },
    ],
  },
  {
    topicId: "23",
    topicName: "Bit Manipulation & Number Theory",
    topicDescription:
      "Advanced problems related to bit manipulation and number theory.",
    problems: [
      {
        id: "139",
        name: "Single Number II",
        description: "",
        link: "https://leetcode.com/problems/single-number-ii/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [23],
      },
      {
        id: "140",
        name: "Gray Code",
        description: "",
        link: "https://leetcode.com/problems/gray-code/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [23],
      },
      {
        id: "141",
        name: "Maximum XOR of Two Numbers in an Array",
        description: "",
        link: "https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [23],
      },
      {
        id: "142",
        name: "Power of Four",
        description: "",
        link: "https://leetcode.com/problems/power-of-four/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [23],
      },
      {
        id: "143",
        name: "Number of 1 Bits",
        description: "",
        link: "https://leetcode.com/problems/number-of-1-bits/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [23],
      },
      {
        id: "144",
        name: "Sum of Two Integers (Without using + or -)",
        description: "",
        link: "https://leetcode.com/problems/sum-of-two-integers/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [23],
      },
    ],
  },

  {
    topicId: "24",
    topicName: "Miscellaneous & Hardest Problems",
    topicDescription: "Miscellaneous and hardest problems.",
    problems: [
      {
        id: "145",
        name: "Count Different Palindromic Subsequences",
        description: "",
        link: "https://leetcode.com/problems/count-different-palindromic-subsequences/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [24],
      },
      {
        id: "146",
        name: "Number of Ways to Stay in the Same Place After Some Steps",
        description: "",
        link: "https://leetcode.com/problems/number-of-ways-to-stay-in-the-same-place-after-some-steps/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [24],
      },
      {
        id: "147",
        name: "Number of Ways to Reorder Array to Get BST",
        description: "",
        link: "https://leetcode.com/problems/number-of-ways-to-reorder-array-to-get-same-bst/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [24],
      },
      {
        id: "148",
        name: "Find the Shortest Superstring",
        description: "",
        link: "https://leetcode.com/problems/find-the-shortest-superstring/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [24],
      },
      {
        id: "149",
        name: "Minimum Number of Refueling Stops",
        description: "",
        link: "https://leetcode.com/problems/minimum-number-of-refueling-stops/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [24],
      },
      {
        id: "150",
        name: "Reverse Pairs",
        description: "",
        link: "https://leetcode.com/problems/reverse-pairs/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [24],
      },
    ],
  },
];

const DSA_ULTIMATE: DSASheetType[] = [
  {
    topicId: "25",
    topicName: "Advanced Data Structures & Hard Problems",
    topicDescription: "Advanced data structures and hard problems.",
    problems: [
      {
        id: "151",
        name: "Implement a Trie (Prefix Tree)",
        description: "",
        link: "https://leetcode.com/problems/implement-trie-prefix-tree/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "152",
        name: "Word Search II",
        description: "",
        link: "https://leetcode.com/problems/word-search-ii/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "153",
        name: "Longest Duplicate Substring",
        description: "",
        link: "https://leetcode.com/problems/longest-duplicate-substring/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "154",
        name: "Palindrome Pairs",
        description: "",
        link: "https://leetcode.com/problems/palindrome-pairs/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "155",
        name: "Range Sum Query - Mutable",
        description: "",
        link: "https://leetcode.com/problems/range-sum-query-mutable/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "156",
        name: "Count of Smaller Numbers After Self",
        description: "",
        link: "https://leetcode.com/problems/count-of-smaller-numbers-after-self/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "157",
        name: "Reverse Pairs",
        description: "",
        link: "https://leetcode.com/problems/reverse-pairs/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "158",
        name: "Cheapest Flights Within K Stops",
        description: "",
        link: "https://leetcode.com/problems/cheapest-flights-within-k-stops/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "159",
        name: "Find the Shortest Superstring",
        description: "",
        link: "https://leetcode.com/problems/find-the-shortest-superstring/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "160",
        name: "Minimum Cost to Make at Least One Valid Path",
        description: "",
        link: "https://leetcode.com/problems/minimum-cost-to-make-at-least-one-valid-path-in-a-grid/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "161",
        name: "Reconstruct Itinerary",
        description: "",
        link: "https://leetcode.com/problems/reconstruct-itinerary/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "162",
        name: "Course Schedule III",
        description: "",
        link: "https://leetcode.com/problems/course-schedule-iii/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "163",
        name: "Regular Expression Matching",
        description: "",
        link: "https://leetcode.com/problems/regular-expression-matching/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "164",
        name: "Minimum Insertion Steps to Make a String Palindrome",
        description: "",
        link: "https://leetcode.com/problems/minimum-insertion-steps-to-make-a-string-palindrome/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "165",
        name: "Russian Doll Envelopes",
        description: "",
        link: "https://leetcode.com/problems/russian-doll-envelopes/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "166",
        name: "Super Egg Drop",
        description: "",
        link: "https://leetcode.com/problems/super-egg-drop/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "167",
        name: "Minimum Cost to Cut a Stick",
        description: "",
        link: "https://leetcode.com/problems/minimum-cost-to-cut-a-stick/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "168",
        name: "Word Ladder II",
        description: "",
        link: "https://leetcode.com/problems/word-ladder-ii/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "169",
        name: "Count of Distinct Subsequences",
        description: "",
        link: "https://leetcode.com/problems/distinct-subsequences/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "170",
        name: "The Skyline Problem",
        description: "",
        link: "https://leetcode.com/problems/the-skyline-problem/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "171",
        name: "Trapping Rain Water II",
        description: "",
        link: "https://leetcode.com/problems/trapping-rain-water-ii/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "172",
        name: "Minimum Number of Refueling Stops",
        description: "",
        link: "https://leetcode.com/problems/minimum-number-of-refueling-stops/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "173",
        name: "Max Points on a Line",
        description: "",
        link: "https://leetcode.com/problems/max-points-on-a-line/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "174",
        name: "Maximum XOR of Two Numbers in an Array",
        description: "",
        link: "https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "175",
        name: "Median of Two Sorted Arrays",
        description: "",
        link: "https://leetcode.com/problems/median-of-two-sorted-arrays/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "176",
        name: "Integer to English Words",
        description: "",
        link: "https://leetcode.com/problems/integer-to-english-words/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
    ],
  },
  {
    topicId: "26",
    topicName: "Advanced Arrays & Math",
    topicDescription: "Advanced problems related to arrays and math.",
    problems: [
      {
        id: "177",
        name: "Subarray Sum Equals K",
        description: "",
        link: "https://leetcode.com/problems/subarray-sum-equals-k/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [26],
      },
      {
        id: "178",
        name: "Max Chunks To Make Sorted II",
        description: "",
        link: "https://leetcode.com/problems/max-chunks-to-make-sorted-ii/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [26],
      },
      {
        id: "179",
        name: "Count Good Numbers",
        description: "",
        link: "https://leetcode.com/problems/count-good-numbers/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [26],
      },
      {
        id: "180",
        name: "Minimum Moves to Equal Array Elements II",
        description: "",
        link: "https://leetcode.com/problems/minimum-moves-to-equal-array-elements-ii/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [26],
      },
      {
        id: "181",
        name: "Best Meeting Point",
        description: "",
        link: "https://leetcode.com/problems/best-meeting-point/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [26],
      },
      {
        id: "182",
        name: "Jump Game III",
        description: "",
        link: "https://leetcode.com/problems/jump-game-iii/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [26],
      },
      {
        id: "183",
        name: "Rotate Function",
        description: "",
        link: "https://leetcode.com/problems/rotate-function/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [26],
      },
      {
        id: "184",
        name: "Number of Subarrays With Bounded Maximum",
        description: "",
        link: "https://leetcode.com/problems/number-of-subarrays-with-bounded-maximum/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [26],
      },
      {
        id: "185",
        name: "Sum of Distances in Tree",
        description: "",
        link: "https://leetcode.com/problems/sum-of-distances-in-tree/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [26],
      },
      {
        id: "186",
        name: "N-Queens II",
        description: "",
        link: "https://leetcode.com/problems/n-queens-ii/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [26],
      },
    ],
  },
  {
    topicId: "27",
    topicName: "Hard Binary Search Problems",
    topicDescription: "Hard problems related to binary search.",
    problems: [
      {
        id: "187",
        name: "Capacity To Ship Packages Within D Days",
        description: "",
        link: "https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [27],
      },
      {
        id: "188",
        name: "Aggressive Cows (SPOJ - AGGRCOW)",
        description: "",
        link: "https://www.spoj.com/problems/AGGRCOW/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [27],
      },
      {
        id: "189",
        name: "Median of Two Sorted Arrays",
        description: "",
        link: "https://leetcode.com/problems/median-of-two-sorted-arrays/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [27],
      },
      {
        id: "190",
        name: "Kth Smallest Element in a Sorted Matrix",
        description: "",
        link: "https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [27],
      },
      {
        id: "191",
        name: "Find Minimum in Rotated Sorted Array II",
        description: "",
        link: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array-ii/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [27],
      },
      {
        id: "192",
        name: "Split Array Largest Sum",
        description: "",
        link: "https://leetcode.com/problems/split-array-largest-sum/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [27],
      },
      {
        id: "193",
        name: "Find the Smallest Divisor Given a Threshold",
        description: "",
        link: "https://leetcode.com/problems/find-the-smallest-divisor-given-a-threshold/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [27],
      },
      {
        id: "194",
        name: "Magnetic Force Between Two Balls",
        description: "",
        link: "https://leetcode.com/problems/magnetic-force-between-two-balls/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [27],
      },
      {
        id: "195",
        name: "Minimum Number of Days to Make m Bouquets",
        description: "",
        link: "https://leetcode.com/problems/minimum-number-of-days-to-make-m-bouquets/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [27],
      },
      {
        id: "196",
        name: "Cutting Ribbons",
        description: "",
        link: "https://leetcode.com/problems/cutting-ribbons/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [27],
      },
    ],
  },

  {
    topicId: "25",
    topicName: "Advanced Data Structures & Hard Problems",
    topicDescription: "Advanced data structures and hard problems.",
    problems: [
      {
        id: "151",
        name: "Implement a Trie (Prefix Tree)",
        description: "",
        link: "https://leetcode.com/problems/implement-trie-prefix-tree/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "152",
        name: "Word Search II",
        description: "",
        link: "https://leetcode.com/problems/word-search-ii/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "153",
        name: "Longest Duplicate Substring",
        description: "",
        link: "https://leetcode.com/problems/longest-duplicate-substring/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "154",
        name: "Palindrome Pairs",
        description: "",
        link: "https://leetcode.com/problems/palindrome-pairs/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "155",
        name: "Range Sum Query - Mutable",
        description: "",
        link: "https://leetcode.com/problems/range-sum-query-mutable/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "156",
        name: "Count of Smaller Numbers After Self",
        description: "",
        link: "https://leetcode.com/problems/count-of-smaller-numbers-after-self/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "157",
        name: "Reverse Pairs",
        description: "",
        link: "https://leetcode.com/problems/reverse-pairs/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "158",
        name: "Cheapest Flights Within K Stops",
        description: "",
        link: "https://leetcode.com/problems/cheapest-flights-within-k-stops/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "159",
        name: "Find the Shortest Superstring",
        description: "",
        link: "https://leetcode.com/problems/find-the-shortest-superstring/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "160",
        name: "Minimum Cost to Make at Least One Valid Path",
        description: "",
        link: "https://leetcode.com/problems/minimum-cost-to-make-at-least-one-valid-path-in-a-grid/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "161",
        name: "Reconstruct Itinerary",
        description: "",
        link: "https://leetcode.com/problems/reconstruct-itinerary/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "162",
        name: "Course Schedule III",
        description: "",
        link: "https://leetcode.com/problems/course-schedule-iii/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "163",
        name: "Regular Expression Matching",
        description: "",
        link: "https://leetcode.com/problems/regular-expression-matching/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "164",
        name: "Minimum Insertion Steps to Make a String Palindrome",
        description: "",
        link: "https://leetcode.com/problems/minimum-insertion-steps-to-make-a-string-palindrome/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "165",
        name: "Russian Doll Envelopes",
        description: "",
        link: "https://leetcode.com/problems/russian-doll-envelopes/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "166",
        name: "Super Egg Drop",
        description: "",
        link: "https://leetcode.com/problems/super-egg-drop/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "167",
        name: "Minimum Cost to Cut a Stick",
        description: "",
        link: "https://leetcode.com/problems/minimum-cost-to-cut-a-stick/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "168",
        name: "Word Ladder II",
        description: "",
        link: "https://leetcode.com/problems/word-ladder-ii/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "169",
        name: "Count of Distinct Subsequences",
        description: "",
        link: "https://leetcode.com/problems/distinct-subsequences/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "170",
        name: "The Skyline Problem",
        description: "",
        link: "https://leetcode.com/problems/the-skyline-problem/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "171",
        name: "Trapping Rain Water II",
        description: "",
        link: "https://leetcode.com/problems/trapping-rain-water-ii/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "172",
        name: "Minimum Number of Refueling Stops",
        description: "",
        link: "https://leetcode.com/problems/minimum-number-of-refueling-stops/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "173",
        name: "Max Points on a Line",
        description: "",
        link: "https://leetcode.com/problems/max-points-on-a-line/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "174",
        name: "Maximum XOR of Two Numbers in an Array",
        description: "",
        link: "https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "175",
        name: "Median of Two Sorted Arrays",
        description: "",
        link: "https://leetcode.com/problems/median-of-two-sorted-arrays/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
      {
        id: "176",
        name: "Integer to English Words",
        description: "",
        link: "https://leetcode.com/problems/integer-to-english-words/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [25],
      },
    ],
  },
  {
    topicId: "26",
    topicName: "Advanced Arrays & Math",
    topicDescription: "Advanced problems related to arrays and math.",
    problems: [
      {
        id: "177",
        name: "Subarray Sum Equals K",
        description: "",
        link: "https://leetcode.com/problems/subarray-sum-equals-k/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [26],
      },
      {
        id: "178",
        name: "Max Chunks To Make Sorted II",
        description: "",
        link: "https://leetcode.com/problems/max-chunks-to-make-sorted-ii/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [26],
      },
      {
        id: "179",
        name: "Count Good Numbers",
        description: "",
        link: "https://leetcode.com/problems/count-good-numbers/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [26],
      },
      {
        id: "180",
        name: "Minimum Moves to Equal Array Elements II",
        description: "",
        link: "https://leetcode.com/problems/minimum-moves-to-equal-array-elements-ii/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [26],
      },
      {
        id: "181",
        name: "Best Meeting Point",
        description: "",
        link: "https://leetcode.com/problems/best-meeting-point/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [26],
      },
      {
        id: "182",
        name: "Jump Game III",
        description: "",
        link: "https://leetcode.com/problems/jump-game-iii/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [26],
      },
      {
        id: "183",
        name: "Rotate Function",
        description: "",
        link: "https://leetcode.com/problems/rotate-function/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [26],
      },
      {
        id: "184",
        name: "Number of Subarrays With Bounded Maximum",
        description: "",
        link: "https://leetcode.com/problems/number-of-subarrays-with-bounded-maximum/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [26],
      },
      {
        id: "185",
        name: "Sum of Distances in Tree",
        description: "",
        link: "https://leetcode.com/problems/sum-of-distances-in-tree/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [26],
      },
      {
        id: "186",
        name: "N-Queens II",
        description: "",
        link: "https://leetcode.com/problems/n-queens-ii/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [26],
      },
    ],
  },
  {
    topicId: "27",
    topicName: "Hard Binary Search Problems",
    topicDescription: "Hard problems related to binary search.",
    problems: [
      {
        id: "187",
        name: "Capacity To Ship Packages Within D Days",
        description: "",
        link: "https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [27],
      },
      {
        id: "188",
        name: "Aggressive Cows (SPOJ - AGGRCOW)",
        description: "",
        link: "https://www.spoj.com/problems/AGGRCOW/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [27],
      },
      {
        id: "189",
        name: "Median of Two Sorted Arrays",
        description: "",
        link: "https://leetcode.com/problems/median-of-two-sorted-arrays/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [27],
      },
      {
        id: "190",
        name: "Kth Smallest Element in a Sorted Matrix",
        description: "",
        link: "https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [27],
      },
      {
        id: "191",
        name: "Find Minimum in Rotated Sorted Array II",
        description: "",
        link: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array-ii/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [27],
      },
      {
        id: "192",
        name: "Split Array Largest Sum",
        description: "",
        link: "https://leetcode.com/problems/split-array-largest-sum/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [27],
      },
      {
        id: "193",
        name: "Find the Smallest Divisor Given a Threshold",
        description: "",
        link: "https://leetcode.com/problems/find-the-smallest-divisor-given-a-threshold/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [27],
      },
      {
        id: "194",
        name: "Magnetic Force Between Two Balls",
        description: "",
        link: "https://leetcode.com/problems/magnetic-force-between-two-balls/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [27],
      },
      {
        id: "195",
        name: "Minimum Number of Days to Make m Bouquets",
        description: "",
        link: "https://leetcode.com/problems/minimum-number-of-days-to-make-m-bouquets/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [27],
      },
      {
        id: "196",
        name: "Cutting Ribbons",
        description: "",
        link: "https://leetcode.com/problems/cutting-ribbons/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [27],
      },
    ],
  },
  {
    topicId: "28",
    topicName: "Advanced Recursion & Backtracking",
    topicDescription:
      "Advanced problems related to recursion and backtracking.",
    problems: [
      {
        id: "197",
        name: "Word Search II",
        description: "",
        link: "https://leetcode.com/problems/word-search-ii/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [28],
      },
      {
        id: "198",
        name: "The Skyline Problem",
        description: "",
        link: "https://leetcode.com/problems/the-skyline-problem/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [28],
      },
      {
        id: "199",
        name: "Word Break II",
        description: "",
        link: "https://leetcode.com/problems/word-break-ii/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [28],
      },
      {
        id: "200",
        name: "Brace Expansion II",
        description: "",
        link: "https://leetcode.com/problems/brace-expansion-ii/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [28],
      },
      {
        id: "201",
        name: "Matchsticks to Square",
        description: "",
        link: "https://leetcode.com/problems/matchsticks-to-square/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [28],
      },
      {
        id: "202",
        name: "Sudoku Solver",
        description: "",
        link: "https://leetcode.com/problems/sudoku-solver/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [28],
      },
      {
        id: "203",
        name: "Kth Smallest Path in a Grid",
        description: "",
        link: "https://leetcode.com/problems/kth-smallest-instructions/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [28],
      },
      {
        id: "204",
        name: "Count Ways to Make Target Array",
        description: "",
        link: "https://leetcode.com/problems/number-of-ways-to-reorder-array-to-get-same-bst/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [28],
      },
      {
        id: "205",
        name: "Unique Paths III",
        description: "",
        link: "https://leetcode.com/problems/unique-paths-iii/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [28],
      },
      {
        id: "206",
        name: "Reconstruct Itinerary",
        description: "",
        link: "https://leetcode.com/problems/reconstruct-itinerary/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [28],
      },
    ],
  },
  {
    topicId: "29",
    topicName: "Advanced Graph Theory & Shortest Paths",
    topicDescription:
      "Advanced problems related to graph theory and shortest paths.",
    problems: [
      {
        id: "207",
        name: "Cheapest Flights Within K Stops",
        description: "",
        link: "https://leetcode.com/problems/cheapest-flights-within-k-stops/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [29],
      },
      {
        id: "208",
        name: "Find the Shortest Superstring",
        description: "",
        link: "https://leetcode.com/problems/find-the-shortest-superstring/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [29],
      },
      {
        id: "209",
        name: "Minimum Cost to Make at Least One Valid Path",
        description: "",
        link: "https://leetcode.com/problems/minimum-cost-to-make-at-least-one-valid-path-in-a-grid/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [29],
      },
      {
        id: "210",
        name: "Course Schedule III",
        description: "",
        link: "https://leetcode.com/problems/course-schedule-iii/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [29],
      },
      {
        id: "211",
        name: "Maximum Number of Events That Can Be Attended",
        description: "",
        link: "https://leetcode.com/problems/maximum-number-of-events-that-can-be-attended/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [29],
      },
      {
        id: "212",
        name: "Swim in Rising Water",
        description: "",
        link: "https://leetcode.com/problems/swim-in-rising-water/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [29],
      },
      {
        id: "213",
        name: "Optimize Water Distribution in a Village",
        description: "",
        link: "https://leetcode.com/problems/optimize-water-distribution-in-a-village/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [29],
      },
      {
        id: "214",
        name: "Reachable Nodes in a Graph",
        description: "",
        link: "https://leetcode.com/problems/reachable-nodes-in-subdivided-graph/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [29],
      },
      {
        id: "215",
        name: "Min Cost to Connect All Points",
        description: "",
        link: "https://leetcode.com/problems/min-cost-to-connect-all-points/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [29],
      },
      {
        id: "216",
        name: "Graph Connectivity With Threshold",
        description: "",
        link: "https://leetcode.com/problems/graph-connectivity-with-threshold/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [29],
      },
    ],
  },
  {
    topicId: "30",
    topicName: "Segment Tree & Hard Data Structures",
    topicDescription:
      "Advanced problems related to segment trees and other hard data structures.",
    problems: [
      {
        id: "217",
        name: "Range Sum Query - Mutable",
        description: "",
        link: "https://leetcode.com/problems/range-sum-query-mutable/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [30],
      },
      {
        id: "218",
        name: "Count of Smaller Numbers After Self",
        description: "",
        link: "https://leetcode.com/problems/count-of-smaller-numbers-after-self/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [30],
      },
      {
        id: "219",
        name: "Reverse Pairs",
        description: "",
        link: "https://leetcode.com/problems/reverse-pairs/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [30],
      },
      {
        id: "220",
        name: "Design Skiplist",
        description: "",
        link: "https://leetcode.com/problems/design-skiplist/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [30],
      },
      {
        id: "221",
        name: "Design a Food Rating System",
        description: "",
        link: "https://leetcode.com/problems/design-a-food-rating-system/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [30],
      },
      {
        id: "222",
        name: "Top K Frequent Words",
        description: "",
        link: "https://leetcode.com/problems/top-k-frequent-words/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [30],
      },
      {
        id: "223",
        name: "LRU Cache",
        description: "",
        link: "https://leetcode.com/problems/lru-cache/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [30],
      },
      {
        id: "224",
        name: "LFU Cache",
        description: "",
        link: "https://leetcode.com/problems/lfu-cache/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [30],
      },
      {
        id: "225",
        name: "All O`one Data Structure",
        description: "",
        link: "https://leetcode.com/problems/all-oone-data-structure/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [30],
      },
      {
        id: "226",
        name: "Design Twitter",
        description: "",
        link: "https://leetcode.com/problems/design-twitter/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [30],
      },
      {
        id: "227",
        name: "Design In-Memory File System",
        description: "",
        link: "https://leetcode.com/problems/design-in-memory-file-system/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [30],
      },
      {
        id: "228",
        name: "Design Search Autocomplete System",
        description: "",
        link: "https://leetcode.com/problems/design-search-autocomplete-system/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [30],
      },
      {
        id: "229",
        name: "Design Add and Search Words Data Structure",
        description: "",
        link: "https://leetcode.com/problems/design-add-and-search-words-data-structure/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [30],
      },
      {
        id: "230",
        name: "Design Hit Counter",
        description: "",
        link: "https://leetcode.com/problems/design-hit-counter/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [30],
      },
      {
        id: "231",
        name: "Design Snake Game",
        description: "",
        link: "https://leetcode.com/problems/design-snake-game/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [30],
      },
      {
        id: "232",
        name: "Design Tic-Tac-Toe",
        description: "",
        link: "https://leetcode.com/problems/design-tic-tac-toe/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [30],
      },
      {
        id: "233",
        name: "Design Circular Queue",
        description: "",
        link: "https://leetcode.com/problems/design-circular-queue/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [30],
      },
      {
        id: "234",
        name: "Design Circular Deque",
        description: "",
        link: "https://leetcode.com/problems/design-circular-deque/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [30],
      },
      {
        id: "235",
        name: "Design Front Middle Back Queue",
        description: "",
        link: "https://leetcode.com/problems/design-front-middle-back-queue/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [30],
      },
      {
        id: "236",
        name: "Design Browser History",
        description: "",
        link: "https://leetcode.com/problems/design-browser-history/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [30],
      },
      {
        id: "237",
        name: "Design Parking System",
        description: "",
        link: "https://leetcode.com/problems/design-parking-system/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [30],
      },
      {
        id: "238",
        name: "Design Underground System",
        description: "",
        link: "https://leetcode.com/problems/design-underground-system/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [30],
      },
      {
        id: "239",
        name: "Design File System",
        description: "",
        link: "https://leetcode.com/problems/design-file-system/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [30],
      },
      {
        id: "240",
        name: "Design Log Storage System",
        description: "",
        link: "https://leetcode.com/problems/design-log-storage-system/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [30],
      },
      {
        id: "241",
        name: "Design In-Memory File System",
        description: "",
        link: "https://leetcode.com/problems/design-in-memory-file-system/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [30],
      },
      {
        id: "242",
        name: "Design Search Autocomplete System",
        description: "",
        link: "https://leetcode.com/problems/design-search-autocomplete-system/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [30],
      },
      {
        id: "243",
        name: "Design Add and Search Words Data Structure",
        description: "",
        link: "https://leetcode.com/problems/design-add-and-search-words-data-structure/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [30],
      },
      {
        id: "244",
        name: "Design Hit Counter",
        description: "",
        link: "https://leetcode.com/problems/design-hit-counter/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [30],
      },
      {
        id: "245",
        name: "Design Snake Game",
        description: "",
        link: "https://leetcode.com/problems/design-snake-game/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [30],
      },
      {
        id: "246",
        name: "Design Tic-Tac-Toe",
        description: "",
        link: "https://leetcode.com/problems/design-tic-tac-toe/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [30],
      },
      {
        id: "247",
        name: "Design Circular Queue",
        description: "",
        link: "https://leetcode.com/problems/design-circular-queue/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [30],
      },
      {
        id: "248",
        name: "Design Circular Deque",
        description: "",
        link: "https://leetcode.com/problems/design-circular-deque/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [30],
      },
      {
        id: "249",
        name: "Design Front Middle Back Queue",
        description: "",
        link: "https://leetcode.com/problems/design-front-middle-back-queue/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [30],
      },
      {
        id: "250",
        name: "Design Browser History",
        description: "",
        link: "https://leetcode.com/problems/design-browser-history/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [30],
      },
      {
        id: "251",
        name: "Design Parking System",
        description: "",
        link: "https://leetcode.com/problems/design-parking-system/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [30],
      },
      {
        id: "252",
        name: "Design Underground System",
        description: "",
        link: "https://leetcode.com/problems/design-underground-system/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [30],
      },
      {
        id: "253",
        name: "Design File System",
        description: "",
        link: "https://leetcode.com/problems/design-file-system/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [30],
      },
      {
        id: "254",
        name: "Design Log Storage System",
        description: "",
        link: "https://leetcode.com/problems/design-log-storage-system/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [30],
      },
    ],
  },
];

export { DSA_POWERSET, DSA_ULTIMATE };
