import { DSASheetType } from "./dsa-sheet-type";
import { ARRAY_AND_STRING } from "./topics-problems/array-and-string";
import { BIT_MANIPULATION_AND_GREEDY } from "./topics-problems/bit-manipulation-and-greedy";
import {
  ADVANCE_DYNAMIC_PROGRAMMING,
  DYNAMIC_PROGRAMMING,
} from "./topics-problems/dynamic-programming";
import { GRAPHS, ADVANCE_GRAPHS } from "./topics-problems/graphs";
import { LINKED_LIST } from "./topics-problems/linked-list";
import { RECURSION_AND_BACKTRACKING } from "./topics-problems/recursion-and-backtracking";
import { SEARCHING_AND_SORTING } from "./topics-problems/searching-and-sorting";
import { STACK_AND_QUEUE } from "./topics-problems/stack-and-queue";
import { TREES_AND_BINARY_SEARCH_TREES } from "./topics-problems/trees-and-binary-search-trees";

const DSA_SHEET: DSASheetType[] = [
  {
    topicId: "1",
    topicName: "Arrays & Strings",
    topicDescription: "Problems related to arrays and strings.",
    problems: ARRAY_AND_STRING,
  },
  {
    topicId: "2",
    topicName: "Searching & Sorting",
    topicDescription: "Problems related to searching and sorting algorithms.",
    problems: SEARCHING_AND_SORTING,
  },
  {
    topicId: "3",
    topicName: "Recursion & Backtracking",
    topicDescription: "Problems related to recursion and backtracking.",
    problems: RECURSION_AND_BACKTRACKING,
  },
  {
    topicId: "4",
    topicName: "Linked List",
    topicDescription: "Problems related to linked lists.",
    problems: LINKED_LIST,
  },
  {
    topicId: "5",
    topicName: "Stack & Queue",
    topicDescription: "Problems related to stacks and queues.",
    problems: STACK_AND_QUEUE,
  },
  {
    topicId: "6",
    topicName: "Trees & Binary Search Trees",
    topicDescription: "Problems related to trees and binary search trees.",
    problems: TREES_AND_BINARY_SEARCH_TREES,
  },
  {
    topicId: "7",
    topicName: "Graphs",
    topicDescription: "Problems related to graphs.",
    problems: GRAPHS,
  },
  {
    topicId: "8",
    topicName: "Dynamic Programming",
    topicDescription: "Problems related to dynamic programming.",
    problems: DYNAMIC_PROGRAMMING,
  },
  {
    topicId: "9",
    topicName: "Bit Manipulation & Greedy",
    topicDescription:
      "Problems related to bit manipulation and greedy algorithms.",
    problems: BIT_MANIPULATION_AND_GREEDY,
  },
  {
    topicId: "10",
    topicName: "Advanced Graphs",
    topicDescription: "Advanced problems related to graphs.",
    problems: ADVANCE_GRAPHS,
  },
  {
    topicId: "11",
    topicName: "Advanced Dynamic Programming",
    topicDescription: "Advanced problems related to dynamic programming.",
    problems: ADVANCE_DYNAMIC_PROGRAMMING,
  },
  {
    topicId: "12",
    topicName: "Tries & Advanced String Algorithms",
    topicDescription:
      "Problems related to tries and advanced string algorithms.",
    problems: [
      {
        id: "78",
        name: "Implement Trie (Prefix Tree)",
        description: "",
        link: "https://leetcode.com/problems/implement-trie-prefix-tree/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [12],
      },
      {
        id: "79",
        name: "Replace Words",
        description: "",
        link: "https://leetcode.com/problems/replace-words/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [12],
      },
      {
        id: "80",
        name: "Word Search II",
        description: "",
        link: "https://leetcode.com/problems/word-search-ii/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [12],
      },
      {
        id: "81",
        name: "Palindrome Pairs",
        description: "",
        link: "https://leetcode.com/problems/palindrome-pairs/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [12],
      },
    ],
  },
  {
    topicId: "3",
    topicName: "Recursion & Backtracking",
    topicDescription: "Problems related to recursion and backtracking.",
    problems: [
      {
        id: "21",
        name: "Factorial using Recursion",
        description: "",
        link: "https://www.geeksforgeeks.org/recursive-programs-to-find-factorial-of-a-given-number/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Easy",
        cotegoriy: [3],
      },
      {
        id: "22",
        name: "Fibonacci Number",
        description: "",
        link: "https://leetcode.com/problems/fibonacci-number/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Easy",
        cotegoriy: [3],
      },
      {
        id: "23",
        name: "Subsets",
        description: "",
        link: "https://leetcode.com/problems/subsets/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [3],
      },
      {
        id: "24",
        name: "Combination Sum",
        description: "",
        link: "https://leetcode.com/problems/combination-sum/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [3],
      },
      {
        id: "25",
        name: "Letter Combinations of a Phone Number",
        description: "",
        link: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [3],
      },
      {
        id: "26",
        name: "N-Queens",
        description: "",
        link: "https://leetcode.com/problems/n-queens/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [3],
      },
      {
        id: "27",
        name: "Word Search",
        description: "",
        link: "https://leetcode.com/problems/word-search/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [3],
      },
    ],
  },
  {
    topicId: "4",
    topicName: "Linked List",
    topicDescription: "Problems related to linked lists.",
    problems: [
      {
        id: "28",
        name: "Reverse a Linked List",
        description: "",
        link: "https://leetcode.com/problems/reverse-linked-list/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Easy",
        cotegoriy: [4],
      },
      {
        id: "29",
        name: "Merge Two Sorted Lists",
        description: "",
        link: "https://leetcode.com/problems/merge-two-sorted-lists/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Easy",
        cotegoriy: [4],
      },
      {
        id: "30",
        name: "Linked List Cycle",
        description: "",
        link: "https://leetcode.com/problems/linked-list-cycle/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [4],
      },
      {
        id: "31",
        name: "Add Two Numbers",
        description: "",
        link: "https://leetcode.com/problems/add-two-numbers/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [4],
      },
      {
        id: "32",
        name: "Remove Nth Node From End of List",
        description: "",
        link: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [4],
      },
      {
        id: "33",
        name: "LRU Cache",
        description: "",
        link: "https://leetcode.com/problems/lru-cache/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [4],
      },
      {
        id: "34",
        name: "Merge K Sorted Lists",
        description: "",
        link: "https://leetcode.com/problems/merge-k-sorted-lists/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [4],
      },
    ],
  },
  {
    topicId: "5",
    topicName: "Stack & Queue",
    topicDescription: "Problems related to stacks and queues.",
    problems: [
      {
        id: "35",
        name: "Valid Parentheses",
        description: "",
        link: "https://leetcode.com/problems/valid-parentheses/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Easy",
        cotegoriy: [5],
      },
      {
        id: "36",
        name: "Min Stack",
        description: "",
        link: "https://leetcode.com/problems/min-stack/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Easy",
        cotegoriy: [5],
      },
      {
        id: "37",
        name: "Next Greater Element I",
        description: "",
        link: "https://leetcode.com/problems/next-greater-element-i/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [5],
      },
      {
        id: "38",
        name: "Implement Queue using Stacks",
        description: "",
        link: "https://leetcode.com/problems/implement-queue-using-stacks/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [5],
      },
      {
        id: "39",
        name: "Daily Temperatures",
        description: "",
        link: "https://leetcode.com/problems/daily-temperatures/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [5],
      },
      {
        id: "40",
        name: "Largest Rectangle in Histogram",
        description: "",
        link: "https://leetcode.com/problems/largest-rectangle-in-histogram/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [5],
      },
      {
        id: "41",
        name: "Basic Calculator",
        description: "",
        link: "https://leetcode.com/problems/basic-calculator/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [5],
      },
    ],
  },
  {
    topicId: "6",
    topicName: "Trees & Binary Search Trees",
    topicDescription: "Problems related to trees and binary search trees.",
    problems: [
      {
        id: "42",
        name: "Invert Binary Tree",
        description: "",
        link: "https://leetcode.com/problems/invert-binary-tree/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Easy",
        cotegoriy: [6],
      },
      {
        id: "43",
        name: "Maximum Depth of Binary Tree",
        description: "",
        link: "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Easy",
        cotegoriy: [6],
      },
      {
        id: "44",
        name: "Lowest Common Ancestor in BST",
        description: "",
        link: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [6],
      },
      {
        id: "45",
        name: "Diameter of Binary Tree",
        description: "",
        link: "https://leetcode.com/problems/diameter-of-binary-tree/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [6],
      },
      {
        id: "46",
        name: "Binary Tree Level Order Traversal",
        description: "",
        link: "https://leetcode.com/problems/binary-tree-level-order-treversel/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [6],
      },
      {
        id: "47",
        name: "Serialize and Deserialize a Binary Tree",
        description: "",
        link: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [6],
      },
      {
        id: "48",
        name: "Binary Tree Maximum Path Sum",
        description: "",
        link: "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [6],
      },
    ],
  },
  {
    topicId: "7",
    topicName: "Graphs",
    topicDescription: "Problems related to graphs.",
    problems: [
      {
        id: "49",
        name: "Number of Islands",
        description: "",
        link: "https://leetcode.com/problems/number-of-islands/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Easy",
        cotegoriy: [7],
      },
      {
        id: "50",
        name: "Flood Fill",
        description: "",
        link: "https://leetcode.com/problems/flood-fill/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Easy",
        cotegoriy: [7],
      },
      {
        id: "51",
        name: "Course Schedule",
        description: "",
        link: "https://leetcode.com/problems/course-schedule/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [7],
      },
      {
        id: "52",
        name: "Network Delay Time",
        description: "",
        link: "https://leetcode.com/problems/network-delay-time/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [7],
      },
      {
        id: "53",
        name: "Graph Valid Tree",
        description: "",
        link: "https://leetcode.com/problems/graph-valid-tree/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [7],
      },
      {
        id: "54",
        name: "Word Ladder",
        description: "",
        link: "https://leetcode.com/problems/word-ladder/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [7],
      },
      {
        id: "55",
        name: "Shortest Path in a Grid with Obstacles Elimination",
        description: "",
        link: "https://leetcode.com/problems/shortest-path-in-a-grid-with-obstacles-elimination/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [7],
      },
    ],
  },
  {
    topicId: "8",
    topicName: "Dynamic Programming",
    topicDescription: "Problems related to dynamic programming.",
    problems: [
      {
        id: "56",
        name: "Climbing Stairs",
        description: "",
        link: "https://leetcode.com/problems/climbing-stairs/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Easy",
        cotegoriy: [8],
      },
      {
        id: "57",
        name: "House Robber",
        description: "",
        link: "https://leetcode.com/problems/house-robber/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Easy",
        cotegoriy: [8],
      },
      {
        id: "58",
        name: "Longest Palindromic Substring",
        description: "",
        link: "https://leetcode.com/problems/longest-palindromic-substring/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [8],
      },
      {
        id: "59",
        name: "Partition Equal Subset Sum",
        description: "",
        link: "https://leetcode.com/problems/partition-equal-subset-sum/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [8],
      },
      {
        id: "60",
        name: "Coin Change",
        description: "",
        link: "https://leetcode.com/problems/coin-change/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [8],
      },
      {
        id: "61",
        name: "Edit Distance",
        description: "",
        link: "https://leetcode.com/problems/edit-distance/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [8],
      },
      {
        id: "62",
        name: "Longest Increasing Path in a Matrix",
        description: "",
        link: "https://leetcode.com/problems/longest-increasing-path-in-a-matrix/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [8],
      },
    ],
  },
  {
    topicId: "9",
    topicName: "Bit Manipulation & Greedy",
    topicDescription:
      "Problems related to bit manipulation and greedy algorithms.",
    problems: [
      {
        id: "63",
        name: "Single Number",
        description: "",
        link: "https://leetcode.com/problems/single-number/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Easy",
        cotegoriy: [9],
      },
      {
        id: "64",
        name: "Hamming Distance",
        description: "",
        link: "https://leetcode.com/problems/hamming-distance/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Easy",
        cotegoriy: [9],
      },
      {
        id: "65",
        name: "Jump Game",
        description: "",
        link: "https://leetcode.com/problems/jump-game/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [9],
      },
      {
        id: "66",
        name: "Job Sequencing Problem (GFG)",
        description: "",
        link: "https://www.geeksforgeeks.org/job-sequencing-problem/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [9],
      },
      {
        id: "67",
        name: "Maximum XOR of Two Numbers in an Array",
        description: "",
        link: "https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [9],
      },
    ],
  },
  {
    topicId: "10",
    topicName: "Advanced Graphs",
    topicDescription: "Advanced problems related to graphs.",
    problems: [
      {
        id: "68",
        name: "Find the Town Judge",
        description: "",
        link: "https://leetcode.com/problems/find-the-town-judge/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Easy",
        cotegoriy: [10],
      },
      {
        id: "69",
        name: "Is Graph Bipartite?",
        description: "",
        link: "https://leetcode.com/problems/is-graph-bipartite/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Easy",
        cotegoriy: [10],
      },
      {
        id: "70",
        name: "Clone Graph",
        description: "",
        link: "https://leetcode.com/problems/clone-graph/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [10],
      },
      {
        id: "71",
        name: "Accounts Merge",
        description: "",
        link: "https://leetcode.com/problems/accounts-merge/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [10],
      },
      {
        id: "72",
        name: "Find the Critical and Pseudo-Critical Edges in Minimum Spanning Tree",
        description: "",
        link: "https://leetcode.com/problems/find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [10],
      },
    ],
  },
  {
    topicId: "11",
    topicName: "Advanced Dynamic Programming",
    topicDescription: "Advanced problems related to dynamic programming.",
    problems: [
      {
        id: "73",
        name: "Decode Ways",
        description: "",
        link: "https://leetcode.com/problems/decode-ways/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [11],
      },
      {
        id: "74",
        name: "Unique Paths",
        description: "",
        link: "https://leetcode.com/problems/unique-paths/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [11],
      },
      {
        id: "75",
        name: "Interleaving String",
        description: "",
        link: "https://leetcode.com/problems/interleaving-string/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [11],
      },
      {
        id: "76",
        name: "Burst Balloons",
        description: "",
        link: "https://leetcode.com/problems/burst-balloons/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [11],
      },
      {
        id: "77",
        name: "Palindrome Partitioning II",
        description: "",
        link: "https://leetcode.com/problems/palindrome-partitioning-ii/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [11],
      },
    ],
  },
  {
    topicId: "12",
    topicName: "Tries & Advanced String Algorithms",
    topicDescription:
      "Problems related to tries and advanced string algorithms.",
    problems: [
      {
        id: "78",
        name: "Implement Trie (Prefix Tree)",
        description: "",
        link: "https://leetcode.com/problems/implement-trie-prefix-tree/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [12],
      },
      {
        id: "79",
        name: "Replace Words",
        description: "",
        link: "https://leetcode.com/problems/replace-words/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [12],
      },
      {
        id: "80",
        name: "Word Search II",
        description: "",
        link: "https://leetcode.com/problems/word-search-ii/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [12],
      },
      {
        id: "81",
        name: "Palindrome Pairs",
        description: "",
        link: "https://leetcode.com/problems/palindrome-pairs/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [12],
      },
    ],
  },
  {
    topicId: "13",
    topicName: "Bit Manipulation & Number Theory",
    topicDescription: "Problems related to bit manipulation and number theory.",
    problems: [
      {
        id: "82",
        name: "Power of Two",
        description: "",
        link: "https://leetcode.com/problems/power-of-two/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Easy",
        cotegoriy: [13],
      },
      {
        id: "83",
        name: "Counting Bits",
        description: "",
        link: "https://leetcode.com/problems/counting-bits/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [13],
      },
      {
        id: "84",
        name: "Divide Two Integers",
        description: "",
        link: "https://leetcode.com/problems/divide-two-integers/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [13],
      },
    ],
  },
  {
    topicId: "14",
    topicName: "Miscellaneous Problems",
    topicDescription: "Miscellaneous problems.",
    problems: [
      {
        id: "85",
        name: "LFU Cache",
        description: "",
        link: "https://leetcode.com/problems/lfu-cache/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [14],
      },
      {
        id: "86",
        name: "Find Median from Data Stream",
        description: "",
        link: "https://leetcode.com/problems/find-median-from-data-stream/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [14],
      },
      {
        id: "87",
        name: "Design Twitter",
        description: "",
        link: "https://leetcode.com/problems/design-twitter/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [14],
      },
      {
        id: "88",
        name: "The Skyline Problem",
        description: "",
        link: "https://leetcode.com/problems/the-skyline-problem/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Medium",
        cotegoriy: [14],
      },
      {
        id: "89",
        name: "Regular Expression Matching",
        description: "",
        link: "https://leetcode.com/problems/regular-expression-matching/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [14],
      },
      {
        id: "90",
        name: "Alien Dictionary (Topological Sort)",
        description: "",
        link: "https://leetcode.com/problems/alien-dictionary/",
        guideLink: "",
        videoLink: "",
        deficultyLevel: "Hard",
        cotegoriy: [14],
      },
    ],
  },
];

export default DSA_SHEET;
