import { DSASheetProblemType } from "../dsa-sheet-type";

export const ARRAY_AND_STRING: DSASheetProblemType[] = [
  {
    id: "1",
    name: "Two Sum",
    description: "",
    link: "https://leetcode.com/problems/two-sum/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Easy",
    cotegoriy: [1],
  },
  {
    id: "2",
    name: "Best Time to Buy and Sell Stock",
    description: "",
    link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Easy",
    cotegoriy: [1],
  },
  {
    id: "3",
    name: "Move Zeroes",
    description: "",
    link: "https://leetcode.com/problems/move-zeroes/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Easy",
    cotegoriy: [1],
  },
  {
    id: "4",
    name: "Rotate Array",
    description: "",
    link: "https://leetcode.com/problems/rotate-array/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Easy",
    cotegoriy: [1],
  },
  {
    id: "5",
    name: "Reverse String",
    description: "",
    link: "https://leetcode.com/problems/reverse-string/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Easy",
    cotegoriy: [1],
  },
  {
    id: "6",
    name: "3Sum",
    description: "",
    link: "https://leetcode.com/problems/3sum/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Medium",
    cotegoriy: [1],
  },
  {
    id: "7",
    name: "Longest Substring Without Repeating Characters",
    description: "",
    link: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Medium",
    cotegoriy: [1],
  },
  {
    id: "8",
    name: "Next Permutation",
    description: "",
    link: "https://leetcode.com/problems/next-permutation/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Medium",
    cotegoriy: [1],
  },
  {
    id: "9",
    name: "Container With Most Water",
    description: "",
    link: "https://leetcode.com/problems/container-with-most-water/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Medium",
    cotegoriy: [1],
  },
  {
    id: "10",
    name: "Longest Palindromic Substring",
    description: "",
    link: "https://leetcode.com/problems/longest-palindromic-substring/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Medium",
    cotegoriy: [1],
  },
  {
    id: "11",
    name: "Trapping Rain Water",
    description: "",
    link: "https://leetcode.com/problems/trapping-rain-water/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Hard",
    cotegoriy: [1],
  },
  {
    id: "12",
    name: "Sliding Window Maximum",
    description: "",
    link: "https://leetcode.com/problems/sliding-window-maximum/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Hard",
    cotegoriy: [1],
  },
  {
    id: "13",
    name: "Regular Expression Matching",
    description: "",
    link: "https://leetcode.com/problems/regular-expression-matching/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Hard",
    cotegoriy: [1],
  },
  {
    id: "14",
    name: "Wildcard Matching",
    description: "",
    link: "https://leetcode.com/problems/wildcard-matching/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Hard",
    cotegoriy: [1],
  },
  {
    id: "15",
    name: "Median of Two Sorted Arrays",
    description: "",
    link: "https://leetcode.com/problems/median-of-two-sorted-arrays/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Hard",
    cotegoriy: [1],
  },
];
