import { DSASheetProblemType } from "../dsa-sheet-type";

export const BIT_MANIPULATION_AND_GREEDY: DSASheetProblemType[] = [
  {
    id: "63",
    name: "Single Number",
    description: "",
    link: "https://leetcode.com/problems/single-number/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Easy",
    cotegoriy: [9],
  },
  {
    id: "64",
    name: "Hamming Distance",
    description: "",
    link: "https://leetcode.com/problems/hamming-distance/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Easy",
    cotegoriy: [9],
  },
  {
    id: "65",
    name: "Jump Game",
    description: "",
    link: "https://leetcode.com/problems/jump-game/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Medium",
    cotegoriy: [9],
  },
  {
    id: "66",
    name: "Job Sequencing Problem (GFG)",
    description: "",
    link: "https://www.geeksforgeeks.org/job-sequencing-problem/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Medium",
    cotegoriy: [9],
  },
  {
    id: "67",
    name: "Maximum XOR of Two Numbers in an Array",
    description: "",
    link: "https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Hard",
    cotegoriy: [9],
  },
];
