import { DSASheetProblemType } from "../dsa-sheet-type";

export const DYNAMIC_PROGRAMMING: DSASheetProblemType[] = [
  {
    id: "56",
    name: "Climbing Stairs",
    description: "",
    link: "https://leetcode.com/problems/climbing-stairs/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Easy",
    cotegoriy: [8],
  },
  {
    id: "57",
    name: "House Robber",
    description: "",
    link: "https://leetcode.com/problems/house-robber/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Easy",
    cotegoriy: [8],
  },
  {
    id: "58",
    name: "Longest Palindromic Substring",
    description: "",
    link: "https://leetcode.com/problems/longest-palindromic-substring/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Medium",
    cotegoriy: [8],
  },
  {
    id: "59",
    name: "Partition Equal Subset Sum",
    description: "",
    link: "https://leetcode.com/problems/partition-equal-subset-sum/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Medium",
    cotegoriy: [8],
  },
  {
    id: "60",
    name: "Coin Change",
    description: "",
    link: "https://leetcode.com/problems/coin-change/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Medium",
    cotegoriy: [8],
  },
  {
    id: "61",
    name: "Edit Distance",
    description: "",
    link: "https://leetcode.com/problems/edit-distance/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Hard",
    cotegoriy: [8],
  },
  {
    id: "62",
    name: "Longest Increasing Path in a Matrix",
    description: "",
    link: "https://leetcode.com/problems/longest-increasing-path-in-a-matrix/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Hard",
    cotegoriy: [8],
  },
];

export const ADVANCE_DYNAMIC_PROGRAMMING: DSASheetProblemType[] = [
  {
    id: "73",
    name: "Decode Ways",
    description: "",
    link: "https://leetcode.com/problems/decode-ways/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Medium",
    cotegoriy: [11],
  },
  {
    id: "74",
    name: "Unique Paths",
    description: "",
    link: "https://leetcode.com/problems/unique-paths/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Medium",
    cotegoriy: [11],
  },
  {
    id: "75",
    name: "Interleaving String",
    description: "",
    link: "https://leetcode.com/problems/interleaving-string/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Hard",
    cotegoriy: [11],
  },
  {
    id: "76",
    name: "Burst Balloons",
    description: "",
    link: "https://leetcode.com/problems/burst-balloons/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Hard",
    cotegoriy: [11],
  },
  {
    id: "77",
    name: "Palindrome Partitioning II",
    description: "",
    link: "https://leetcode.com/problems/palindrome-partitioning-ii/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Hard",
    cotegoriy: [11],
  },
];
