import { DSASheetProblemType } from "../dsa-sheet-type";

export const GRAPHS: DSASheetProblemType[] = [
  {
    id: "49",
    name: "Number of Islands",
    description: "",
    link: "https://leetcode.com/problems/number-of-islands/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Easy",
    cotegoriy: [7],
  },
  {
    id: "50",
    name: "Flood Fill",
    description: "",
    link: "https://leetcode.com/problems/flood-fill/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Easy",
    cotegoriy: [7],
  },
  {
    id: "51",
    name: "Course Schedule",
    description: "",
    link: "https://leetcode.com/problems/course-schedule/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Medium",
    cotegoriy: [7],
  },
  {
    id: "52",
    name: "Network Delay Time",
    description: "",
    link: "https://leetcode.com/problems/network-delay-time/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Medium",
    cotegoriy: [7],
  },
  {
    id: "53",
    name: "Graph Valid Tree",
    description: "",
    link: "https://leetcode.com/problems/graph-valid-tree/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Medium",
    cotegoriy: [7],
  },
  {
    id: "54",
    name: "Word Ladder",
    description: "",
    link: "https://leetcode.com/problems/word-ladder/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Hard",
    cotegoriy: [7],
  },
  {
    id: "55",
    name: "Shortest Path in a Grid with Obstacles Elimination",
    description: "",
    link: "https://leetcode.com/problems/shortest-path-in-a-grid-with-obstacles-elimination/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Hard",
    cotegoriy: [7],
  },
];

export const ADVANCE_GRAPHS: DSASheetProblemType[] = [
  {
    id: "68",
    name: "Find the Town Judge",
    description: "",
    link: "https://leetcode.com/problems/find-the-town-judge/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Easy",
    cotegoriy: [10],
  },
  {
    id: "69",
    name: "Is Graph Bipartite?",
    description: "",
    link: "https://leetcode.com/problems/is-graph-bipartite/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Easy",
    cotegoriy: [10],
  },
  {
    id: "70",
    name: "Clone Graph",
    description: "",
    link: "https://leetcode.com/problems/clone-graph/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Medium",
    cotegoriy: [10],
  },
  {
    id: "71",
    name: "Accounts Merge",
    description: "",
    link: "https://leetcode.com/problems/accounts-merge/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Medium",
    cotegoriy: [10],
  },
  {
    id: "72",
    name: "Find the Critical and Pseudo-Critical Edges in Minimum Spanning Tree",
    description: "",
    link: "https://leetcode.com/problems/find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Hard",
    cotegoriy: [10],
  },
];
