import { DSASheetProblemType } from "../dsa-sheet-type";

export const LINKED_LIST: DSASheetProblemType[] = [
  {
    id: "28",
    name: "Reverse a Linked List",
    description: "",
    link: "https://leetcode.com/problems/reverse-linked-list/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Easy",
    cotegoriy: [4],
  },
  {
    id: "29",
    name: "Merge Two Sorted Lists",
    description: "",
    link: "https://leetcode.com/problems/merge-two-sorted-lists/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Easy",
    cotegoriy: [4],
  },
  {
    id: "30",
    name: "Linked List Cycle",
    description: "",
    link: "https://leetcode.com/problems/linked-list-cycle/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Medium",
    cotegoriy: [4],
  },
  {
    id: "31",
    name: "Add Two Numbers",
    description: "",
    link: "https://leetcode.com/problems/add-two-numbers/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Medium",
    cotegoriy: [4],
  },
  {
    id: "32",
    name: "Remove Nth Node From End of List",
    description: "",
    link: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Medium",
    cotegoriy: [4],
  },
  {
    id: "33",
    name: "LRU Cache",
    description: "",
    link: "https://leetcode.com/problems/lru-cache/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Hard",
    cotegoriy: [4],
  },
  {
    id: "34",
    name: "Merge K Sorted Lists",
    description: "",
    link: "https://leetcode.com/problems/merge-k-sorted-lists/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Hard",
    cotegoriy: [4],
  },
];
