import { DSASheetProblemType } from "../dsa-sheet-type";

export const RECURSION_AND_BACKTRACKING: DSASheetProblemType[] = [
  {
    id: "21",
    name: "Factorial using Recursion",
    description: "",
    link: "https://www.geeksforgeeks.org/recursive-programs-to-find-factorial-of-a-given-number/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Easy",
    cotegoriy: [3],
  },
  {
    id: "22",
    name: "Fibonacci Number",
    description: "",
    link: "https://leetcode.com/problems/fibonacci-number/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Easy",
    cotegoriy: [3],
  },
  {
    id: "23",
    name: "Subsets",
    description: "",
    link: "https://leetcode.com/problems/subsets/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Medium",
    cotegoriy: [3],
  },
  {
    id: "24",
    name: "Combination Sum",
    description: "",
    link: "https://leetcode.com/problems/combination-sum/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Medium",
    cotegoriy: [3],
  },
  {
    id: "25",
    name: "Letter Combinations of a Phone Number",
    description: "",
    link: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Medium",
    cotegoriy: [3],
  },
  {
    id: "26",
    name: "N-Queens",
    description: "",
    link: "https://leetcode.com/problems/n-queens/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Hard",
    cotegoriy: [3],
  },
  {
    id: "27",
    name: "Word Search",
    description: "",
    link: "https://leetcode.com/problems/word-search/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Hard",
    cotegoriy: [3],
  },
];
