import { DSASheetProblemType } from "../dsa-sheet-type";

export const SEARCHING_AND_SORTING: DSASheetProblemType[] = [
  {
    id: "16",
    name: "Binary Search",
    description: "",
    link: "https://leetcode.com/problems/binary-search/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Easy",
    cotegoriy: [2],
  },
  {
    id: "17",
    name: "First Bad Version",
    description: "",
    link: "https://leetcode.com/problems/first-bad-version/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Easy",
    cotegoriy: [2],
  },
  {
    id: "18",
    name: "Find Peak Element",
    description: "",
    link: "https://leetcode.com/problems/find-peak-element/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Medium",
    cotegoriy: [2],
  },
  {
    id: "19",
    name: "Search in Rotated Sorted Array",
    description: "",
    link: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Medium",
    cotegoriy: [2],
  },
  {
    id: "20",
    name: "Kth Largest Element in an Array",
    description: "",
    link: "https://leetcode.com/problems/kth-largest-element-in-an-array/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Medium",
    cotegoriy: [2],
  },
];
