import { DSASheetProblemType } from "../dsa-sheet-type";

export const STACK_AND_QUEUE: DSASheetProblemType[] = [
  {
    id: "35",
    name: "Valid Parentheses",
    description: "",
    link: "https://leetcode.com/problems/valid-parentheses/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Easy",
    cotegoriy: [5],
  },
  {
    id: "36",
    name: "Min Stack",
    description: "",
    link: "https://leetcode.com/problems/min-stack/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Easy",
    cotegoriy: [5],
  },
  {
    id: "37",
    name: "Next Greater Element I",
    description: "",
    link: "https://leetcode.com/problems/next-greater-element-i/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Medium",
    cotegoriy: [5],
  },
  {
    id: "38",
    name: "Implement Queue using Stacks",
    description: "",
    link: "https://leetcode.com/problems/implement-queue-using-stacks/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Medium",
    cotegoriy: [5],
  },
  {
    id: "39",
    name: "Daily Temperatures",
    description: "",
    link: "https://leetcode.com/problems/daily-temperatures/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Medium",
    cotegoriy: [5],
  },
  {
    id: "40",
    name: "Largest Rectangle in Histogram",
    description: "",
    link: "https://leetcode.com/problems/largest-rectangle-in-histogram/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Hard",
    cotegoriy: [5],
  },
  {
    id: "41",
    name: "Basic Calculator",
    description: "",
    link: "https://leetcode.com/problems/basic-calculator/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Hard",
    cotegoriy: [5],
  },
];
