import { DSASheetProblemType } from "../dsa-sheet-type";

export const TREES_AND_BINARY_SEARCH_TREES: DSASheetProblemType[] = [
  {
    id: "42",
    name: "Invert Binary Tree",
    description: "",
    link: "https://leetcode.com/problems/invert-binary-tree/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Easy",
    cotegoriy: [6],
  },
  {
    id: "43",
    name: "Maximum Depth of Binary Tree",
    description: "",
    link: "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Easy",
    cotegoriy: [6],
  },
  {
    id: "44",
    name: "Lowest Common Ancestor in BST",
    description: "",
    link: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Medium",
    cotegoriy: [6],
  },
  {
    id: "45",
    name: "Diameter of Binary Tree",
    description: "",
    link: "https://leetcode.com/problems/diameter-of-binary-tree/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Medium",
    cotegoriy: [6],
  },
  {
    id: "46",
    name: "Binary Tree Level Order Traversal",
    description: "",
    link: "https://leetcode.com/problems/binary-tree-level-order-treversel/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Medium",
    cotegoriy: [6],
  },
  {
    id: "47",
    name: "Serialize and Deserialize a Binary Tree",
    description: "",
    link: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Hard",
    cotegoriy: [6],
  },
  {
    id: "48",
    name: "Binary Tree Maximum Path Sum",
    description: "",
    link: "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
    guideLink: "",
    videoLink: "",
    deficultyLevel: "Hard",
    cotegoriy: [6],
  },
];
