import { DSASheetProblemType } from "../../utils/dsa-sheet-type";

export const ARRAY_AND_HASHING: DSASheetProblemType[] = [
  {
    id: "1",
    name: "Two Sum",
    description: "Find two numbers that add up to a specific target.",
    link: "https://leetcode.com/problems/two-sum/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
  {
    id: "2",
    name: "Valid Anagram",
    description: "Check if two strings are anagrams of each other.",
    link: "https://leetcode.com/problems/valid-anagram/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
  {
    id: "3",
    name: "Contains Duplicate",
    description: "Check if any value appears at least twice in the array.",
    link: "https://leetcode.com/problems/contains-duplicate/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
  {
    id: "4",
    name: "Product of Array Except Self",
    description: "Find the product of the array except self.",
    link: "https://leetcode.com/problems/product-of-array-except-self/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "5",
    name: "Encode and Decode Strings",
    description: "Encode and decode a list of strings.",
    link: "https://leetcode.com/problems/encode-and-decode-strings/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "6",
    name: "Group Anagrams",
    description: "Group anagrams together.",
    link: "https://leetcode.com/problems/group-anagrams/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "7",
    name: "Top K Frequent Elements",
    description: "Find the top k frequent elements.",
    link: "https://leetcode.com/problems/top-k-frequent-elements/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "8",
    name: "Longest Consecutive Sequence",
    description: "Find the longest consecutive sequence.",
    link: "https://leetcode.com/problems/longest-consecutive-sequence/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "9",
    name: "4Sum",
    description: "Find four numbers that add up to a specific target.",
    link: "https://leetcode.com/problems/4sum/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "10",
    name: "Subarray Sum Equals K",
    description: "Find the number of subarrays that sum to k.",
    link: "https://leetcode.com/problems/subarray-sum-equals-k/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "11",
    name: "Longest Subarray with Sum K",
    description: "Find the longest subarray with sum k.",
    link: "https://leetcode.com/problems/maximum-size-subarray-sum-equals-k/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "12",
    name: "Count Subarrays with Given XOR",
    description: "Count the number of subarrays with a given XOR.",
    link: "https://www.interviewbit.com/problems/subarray-with-given-xor/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "13",
    name: "Missing Number",
    description: "Find the missing number in the array.",
    link: "https://leetcode.com/problems/missing-number/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
  {
    id: "14",
    name: "Maximum Product Subarray",
    description: "Find the maximum product of a subarray.",
    link: "https://leetcode.com/problems/maximum-product-subarray/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "15",
    name: "Sort Colors",
    description: "Sort an array with colors represented by numbers.",
    link: "https://leetcode.com/problems/sort-colors/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "16",
    name: "Majority Element",
    description: "Find the majority element in the array.",
    link: "https://leetcode.com/problems/majority-element/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
  {
    id: "17",
    name: "Find the Duplicate Number",
    description: "Find the duplicate number in the array.",
    link: "https://leetcode.com/problems/find-the-duplicate-number/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "18",
    name: "Set Matrix Zeroes",
    description: "Set matrix zeroes based on conditions.",
    link: "https://leetcode.com/problems/set-matrix-zeroes/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "19",
    name: "Rotate Image",
    description: "Rotate an image represented by a matrix.",
    link: "https://leetcode.com/problems/rotate-image/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "20",
    name: "Pascal’s Triangle",
    description: "Generate Pascal’s Triangle.",
    link: "https://leetcode.com/problems/pascals-triangle/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
  {
    id: "21",
    name: "3Sum",
    description: "Find three numbers that add up to a specific target.",
    link: "https://leetcode.com/problems/3sum/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "22",
    name: "Maximum Consecutive Ones",
    description: "Find the maximum number of consecutive ones in the array.",
    link: "https://leetcode.com/problems/max-consecutive-ones/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
  {
    id: "23",
    name: "Largest Rectangle in Histogram",
    description: "Find the largest rectangle in a histogram.",
    link: "https://leetcode.com/problems/largest-rectangle-in-histogram/",
    guideLink: "",
    difficultyLevel: "Hard",
  },
  {
    id: "24",
    name: "Insert Interval",
    description: "Insert a new interval into a list of intervals.",
    link: "https://leetcode.com/problems/insert-interval/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "25",
    name: "Merge Intervals",
    description: "Merge overlapping intervals.",
    link: "https://leetcode.com/problems/merge-intervals/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "26",
    name: "Candy",
    description: "Distribute candies to children.",
    link: "https://leetcode.com/problems/candy/",
    guideLink: "",
    difficultyLevel: "Hard",
  },
  {
    id: "27",
    name: "Valid Sudoku",
    description: "Check if a Sudoku board is valid.",
    link: "https://leetcode.com/problems/valid-sudoku/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "28",
    name: "First Missing Positive",
    description: "Find the first missing positive integer.",
    link: "https://leetcode.com/problems/first-missing-positive/",
    guideLink: "",
    difficultyLevel: "Hard",
  },
  {
    id: "29",
    name: "Count Number of Nice Subarrays",
    description: "Count the number of nice subarrays.",
    link: "https://leetcode.com/problems/count-number-of-nice-subarrays/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
];
