import { DSASheetProblemType } from "../../utils/dsa-sheet-type";

export const BIT_MANIPULATION: DSASheetProblemType[] = [
  {
    id: "102",
    name: "Counting Bits",
    description: "",
    link: "https://leetcode.com/problems/counting-bits/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
  {
    id: "59",
    name: "Pow(x, n)",
    description: "",
    link: "https://leetcode.com/problems/powx-n/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "61",
    name: "Reverse Bits",
    description: "",
    link: "https://leetcode.com/problems/reverse-bits/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
  {
    id: "57",
    name: "Bitwise AND of Numbers Range",
    description: "",
    link: "https://leetcode.com/problems/bitwise-and-of-numbers-range/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "153",
    name: "Single Number",
    description: "",
    link: "https://leetcode.com/problems/single-number/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
  {
    id: "154",
    name: "Counting Bits",
    description: "",
    link: "https://leetcode.com/problems/counting-bits/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
  {
    id: "201",
    name: "XOR Queries of a Subarray",
    description: "",
    link: "https://leetcode.com/problems/xor-queries-of-a-subarray/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "202",
    name: "Power of Four",
    description: "",
    link: "https://leetcode.com/problems/power-of-four/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
  {
    id: "252",
    name: "Counting Bits",
    description: "",
    link: "https://leetcode.com/problems/counting-bits/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
  {
    id: "253",
    name: "Reverse Bits",
    description: "",
    link: "https://leetcode.com/problems/reverse-bits/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
  {
    id: "254",
    name: "Single Number",
    description: "",
    link: "https://leetcode.com/problems/single-number/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
];
