import { DSASheetProblemType } from "../../utils/dsa-sheet-type";

export const DYNAMIC_PROGRAMMING: DSASheetProblemType[] = [
  {
    id: "dynamic-programming-1",
    name: "Climbing Stairs",
    description: "",
    link: "https://leetcode.com/problems/climbing-stairs/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
  {
    id: "dynamic-programming-2",
    name: "House Robber",
    description: "",
    link: "https://leetcode.com/problems/house-robber/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "dynamic-programming-3",
    name: "Longest Increasing Subsequence",
    description: "",
    link: "https://leetcode.com/problems/longest-increasing-subsequence/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "dynamic-programming-4",
    name: "Partition Equal Subset Sum",
    description: "",
    link: "https://leetcode.com/problems/partition-equal-subset-sum/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "dynamic-programming-5",
    name: "Word Break",
    description: "",
    link: "https://leetcode.com/problems/word-break/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "dynamic-programming-6",
    name: "Decode Ways",
    description: "",
    link: "https://leetcode.com/problems/decode-ways/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "dynamic-programming-7",
    name: "Unique Paths",
    description: "",
    link: "https://leetcode.com/problems/unique-paths/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "dynamic-programming-8",
    name: "Coin Change",
    description: "",
    link: "https://leetcode.com/problems/coin-change/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "dynamic-programming-9",
    name: "Longest Palindromic Subsequence",
    description: "",
    link: "https://leetcode.com/problems/longest-palindromic-subsequence/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "dynamic-programming-10",
    name: "Wildcard Matching",
    description: "",
    link: "https://leetcode.com/problems/wildcard-matching/",
    guideLink: "",
    difficultyLevel: "Hard",
  },
  {
    id: "dynamic-programming-11",
    name: "Fibonacci Number",
    description: "",
    link: "https://leetcode.com/problems/fibonacci-number/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
  {
    id: "dynamic-programming-12",
    name: "Climbing Stairs",
    description: "",
    link: "https://leetcode.com/problems/climbing-stairs/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
  {
    id: "dynamic-programming-13",
    name: "Longest Increasing Subsequence",
    description: "",
    link: "https://leetcode.com/problems/longest-increasing-subsequence/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "dynamic-programming-14",
    name: "Edit Distance",
    description: "",
    link: "https://leetcode.com/problems/edit-distance/",
    guideLink: "",
    difficultyLevel: "Hard",
  },
  {
    id: "dynamic-programming-15",
    name: "Word Break",
    description: "",
    link: "https://leetcode.com/problems/word-break/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "dynamic-programming-16",
    name: "House Robber",
    description: "",
    link: "https://leetcode.com/problems/house-robber/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "dynamic-programming-17",
    name: "Maximum Subarray",
    description: "",
    link: "https://leetcode.com/problems/maximum-subarray/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "dynamic-programming-18",
    name: "Unique Paths II",
    description: "",
    link: "https://leetcode.com/problems/unique-paths-ii/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "dynamic-programming-19",
    name: "Longest Palindromic Substring",
    description: "",
    link: "https://leetcode.com/problems/longest-palindromic-substring/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "dynamic-programming-20",
    name: "Decode Ways",
    description: "",
    link: "https://leetcode.com/problems/decode-ways/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "dynamic-programming-21",
    name: "Coin Change",
    description: "",
    link: "https://leetcode.com/problems/coin-change/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "dynamic-programming-22",
    name: "Longest Common Subsequence",
    description: "",
    link: "https://leetcode.com/problems/longest-common-subsequence/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "dynamic-programming-23",
    name: "House Robber II",
    description: "",
    link: "https://leetcode.com/problems/house-robber-ii/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "dynamic-programming-24",
    name: "Partition Equal Subset Sum",
    description: "",
    link: "https://leetcode.com/problems/partition-equal-subset-sum/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "dynamic-programming-25",
    name: "Distinct Subsequences",
    description: "",
    link: "https://leetcode.com/problems/distinct-subsequences/",
    guideLink: "",
    difficultyLevel: "Hard",
  },
  {
    id: "dynamic-programming-26",
    name: "Maximum Profit in Job Scheduling",
    description: "",
    link: "https://leetcode.com/problems/maximum-profit-in-job-scheduling/",
    guideLink: "",
    difficultyLevel: "Hard",
  },
  {
    id: "dynamic-programming-27",
    name: "Shortest Bridge",
    description: "",
    link: "https://leetcode.com/problems/shortest-bridge/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "dynamic-programming-28",
    name: "Network Delay Time",
    description: "",
    link: "https://leetcode.com/problems/network-delay-time/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "dynamic-programming-29",
    name: "Critical Connections in a Network",
    description: "",
    link: "https://leetcode.com/problems/critical-connections-in-a-network/",
    guideLink: "",
    difficultyLevel: "Hard",
  },
];
