import { DSASheetProblemType } from "../../utils/dsa-sheet-type";

export const DYNAMIC_PROGRAMMING: DSASheetProblemType[] = [
  {
    id: "52",
    name: "Climbing Stairs",
    description: "",
    link: "https://leetcode.com/problems/climbing-stairs/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
  {
    id: "53",
    name: "House Robber",
    description: "",
    link: "https://leetcode.com/problems/house-robber/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "54",
    name: "Longest Increasing Subsequence",
    description: "",
    link: "https://leetcode.com/problems/longest-increasing-subsequence/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "55",
    name: "Partition Equal Subset Sum",
    description: "",
    link: "https://leetcode.com/problems/partition-equal-subset-sum/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "56",
    name: "Word Break",
    description: "",
    link: "https://leetcode.com/problems/word-break/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "96",
    name: "Decode Ways",
    description: "",
    link: "https://leetcode.com/problems/decode-ways/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "97",
    name: "Unique Paths",
    description: "",
    link: "https://leetcode.com/problems/unique-paths/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "98",
    name: "Coin Change",
    description: "",
    link: "https://leetcode.com/problems/coin-change/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "99",
    name: "Longest Palindromic Subsequence",
    description: "",
    link: "https://leetcode.com/problems/longest-palindromic-subsequence/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "100",
    name: "Wildcard Matching",
    description: "",
    link: "https://leetcode.com/problems/wildcard-matching/",
    guideLink: "",
    difficultyLevel: "Hard",
  },
  {
    id: "138",
    name: "Fibonacci Number",
    description: "",
    link: "https://leetcode.com/problems/fibonacci-number/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
  {
    id: "139",
    name: "Climbing Stairs",
    description: "",
    link: "https://leetcode.com/problems/climbing-stairs/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
  {
    id: "140",
    name: "Longest Increasing Subsequence",
    description: "",
    link: "https://leetcode.com/problems/longest-increasing-subsequence/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "141",
    name: "Edit Distance",
    description: "",
    link: "https://leetcode.com/problems/edit-distance/",
    guideLink: "",
    difficultyLevel: "Hard",
  },
  {
    id: "142",
    name: "Word Break",
    description: "",
    link: "https://leetcode.com/problems/word-break/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "143",
    name: "House Robber",
    description: "",
    link: "https://leetcode.com/problems/house-robber/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "144",
    name: "Maximum Subarray",
    description: "",
    link: "https://leetcode.com/problems/maximum-subarray/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "145",
    name: "Unique Paths II",
    description: "",
    link: "https://leetcode.com/problems/unique-paths-ii/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "146",
    name: "Longest Palindromic Substring",
    description: "",
    link: "https://leetcode.com/problems/longest-palindromic-substring/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "188",
    name: "Decode Ways",
    description: "",
    link: "https://leetcode.com/problems/decode-ways/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "189",
    name: "Coin Change",
    description: "",
    link: "https://leetcode.com/problems/coin-change/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "190",
    name: "Longest Common Subsequence",
    description: "",
    link: "https://leetcode.com/problems/longest-common-subsequence/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "191",
    name: "House Robber II",
    description: "",
    link: "https://leetcode.com/problems/house-robber-ii/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "192",
    name: "Partition Equal Subset Sum",
    description: "",
    link: "https://leetcode.com/problems/partition-equal-subset-sum/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "193",
    name: "Distinct Subsequences",
    description: "",
    link: "https://leetcode.com/problems/distinct-subsequences/",
    guideLink: "",
    difficultyLevel: "Hard",
  },
  {
    id: "194",
    name: "Maximum Profit in Job Scheduling",
    description: "",
    link: "https://leetcode.com/problems/maximum-profit-in-job-scheduling/",
    guideLink: "",
    difficultyLevel: "Hard",
  },
  {
    id: "236",
    name: "Shortest Bridge",
    description: "",
    link: "https://leetcode.com/problems/shortest-bridge/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "237",
    name: "Network Delay Time",
    description: "",
    link: "https://leetcode.com/problems/network-delay-time/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "238",
    name: "Critical Connections in a Network",
    description: "",
    link: "https://leetcode.com/problems/critical-connections-in-a-network/",
    guideLink: "",
    difficultyLevel: "Hard",
  },
];
