import { DSASheetProblemType } from "../../utils/dsa-sheet-type";

export const GRAPHS: DSASheetProblemType[] = [
  {
    id: "1",
    name: "Number of Islands",
    description: "Count the number of islands in a grid.",
    link: "https://leetcode.com/problems/number-of-islands/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "2",
    name: "Rotten Oranges",
    description: "Determine the time required to rot all oranges.",
    link: "https://leetcode.com/problems/rotting-oranges/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "3",
    name: "Course Schedule",
    description: "Determine if you can finish all courses given prerequisites.",
    link: "https://leetcode.com/problems/course-schedule/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "4",
    name: "Alien Dictionary (Topological Sort)",
    description: "Determine the order of characters in an alien language.",
    link: "https://leetcode.com/problems/alien-dictionary/",
    guideLink: "",
    difficultyLevel: "Hard",
  },
  {
    id: "5",
    name: "Word Ladder",
    description:
      "Find the length of the shortest transformation sequence from start to end.",
    link: "https://leetcode.com/problems/word-ladder/",
    guideLink: "",
    difficultyLevel: "Hard",
  },
  {
    id: "6",
    name: "Dijkstra’s Algorithm",
    description:
      "Find the shortest path from a source to all vertices in a weighted graph.",
    link: "https://leetcode.com/problems/network-delay-time/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "7",
    name: "Surrounded Regions",
    description: "Capture all regions surrounded by 'X'.",
    link: "https://leetcode.com/problems/surrounded-regions/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "8",
    name: "Shortest Path in a Grid with Obstacles Elimination",
    description: "Find the shortest path in a grid with obstacles elimination.",
    link: "https://leetcode.com/problems/shortest-path-in-a-grid-with-obstacles-elimination/",
    guideLink: "",
    difficultyLevel: "Hard",
  },
  {
    id: "9",
    name: "Word Ladder II",
    description:
      "Find all shortest transformation sequences from start to end.",
    link: "https://leetcode.com/problems/word-ladder-ii/",
    guideLink: "",
    difficultyLevel: "Hard",
  },
  {
    id: "10",
    name: "Course Schedule II",
    description:
      "Find the order of courses you should take to finish all courses.",
    link: "https://leetcode.com/problems/course-schedule-ii/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "11",
    name: "Redundant Connection",
    description: "Find the redundant connection in a graph.",
    link: "https://leetcode.com/problems/redundant-connection/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "12",
    name: "Number of Connected Components in an Undirected Graph",
    description:
      "Count the number of connected components in an undirected graph.",
    link: "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "13",
    name: "Shortest Bridge",
    description: "Find the shortest bridge between two islands.",
    link: "https://leetcode.com/problems/shortest-bridge/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "14",
    name: "Network Delay Time",
    description: "Find the time it takes for all nodes to receive a signal.",
    link: "https://leetcode.com/problems/network-delay-time/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "15",
    name: "Minimum Cost to Reach Destination in Time",
    description: "Find the minimum cost to reach the destination in time.",
    link: "https://leetcode.com/problems/minimum-cost-to-reach-destination-in-time/",
    guideLink: "",
    difficultyLevel: "Hard",
  },
  {
    id: "16",
    name: "Alien Dictionary (Topological Sort)",
    description: "Determine the order of characters in an alien language.",
    link: "https://www.geeksforgeeks.org/given-sorted-dictionary-find-precedence-characters/",
    guideLink: "",
    difficultyLevel: "Hard",
  },
  {
    id: "17",
    name: "Cheapest Flights Within K Stops",
    description:
      "Find the cheapest price from source to destination with at most k stops.",
    link: "https://leetcode.com/problems/cheapest-flights-within-k-stops/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "18",
    name: "Find the Town Judge",
    description: "Find the town judge in a town of n people.",
    link: "https://leetcode.com/problems/find-the-town-judge/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
  {
    id: "19",
    name: "Shortest Path in Binary Matrix",
    description: "Find the shortest path in a binary matrix.",
    link: "https://leetcode.com/problems/shortest-path-in-binary-matrix/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "20",
    name: "Minimum Spanning Tree (Prim’s Algorithm)",
    description: "Find the minimum spanning tree using Prim’s algorithm.",
    link: "https://www.geeksforgeeks.org/prims-minimum-spanning-tree-mst-greedy-algo-5/",
    guideLink: "",
    difficultyLevel: "Hard",
  },
  {
    id: "21",
    name: "Kruskal’s Algorithm for MST",
    description: "Find the minimum spanning tree using Kruskal’s algorithm.",
    link: "https://www.geeksforgeeks.org/kruskals-algorithm-simple-implementation-for-mst/",
    guideLink: "",
    difficultyLevel: "Hard",
  },
  {
    id: "22",
    name: "Pacific Atlantic Water Flow",
    description:
      "Find the cells where water can flow to both the Pacific and Atlantic ocean.",
    link: "https://leetcode.com/problems/pacific-atlantic-water-flow/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "23",
    name: "Course Schedule II",
    description:
      "Find the order of courses you should take to finish all courses.",
    link: "https://leetcode.com/problems/course-schedule-ii/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "24",
    name: "Redundant Connection",
    description: "Find the redundant connection in a graph.",
    link: "https://leetcode.com/problems/redundant-connection/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "25",
    name: "Number of Connected Components in an Undirected Graph",
    description:
      "Count the number of connected components in an undirected graph.",
    link: "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
];
