import { DSASheetProblemType } from "../../utils/dsa-sheet-type";

export const GREEDY: DSASheetProblemType[] = [
  {
    id: "147",
    name: "Jump Game",
    description: "",
    link: "https://leetcode.com/problems/jump-game/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "148",
    name: "Jump Game II",
    description: "",
    link: "https://leetcode.com/problems/jump-game-ii/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "195",
    name: "Task Scheduler",
    description: "",
    link: "https://leetcode.com/problems/task-scheduler/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "196",
    name: "Minimum Number of Arrows to Burst Balloons",
    description: "",
    link: "https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "239",
    name: "Jump Game",
    description: "",
    link: "https://leetcode.com/problems/jump-game/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "240",
    name: "Edit Distance",
    description: "",
    link: "https://leetcode.com/problems/edit-distance/",
    guideLink: "",
    difficultyLevel: "Hard",
  },
  {
    id: "241",
    name: "Palindromic Substrings",
    description: "",
    link: "https://leetcode.com/problems/palindromic-substrings/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "242",
    name: "Wildcard Matching",
    description: "",
    link: "https://leetcode.com/problems/wildcard-matching/",
    guideLink: "",
    difficultyLevel: "Hard",
  },
  {
    id: "243",
    name: "Buy and Sell Stock with Cooldown",
    description: "",
    link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "244",
    name: "Maximum Product Subarray",
    description: "",
    link: "https://leetcode.com/problems/maximum-product-subarray/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "245",
    name: "Minimum Path Sum",
    description: "",
    link: "https://leetcode.com/problems/minimum-path-sum/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "246",
    name: "Unique Paths II",
    description: "",
    link: "https://leetcode.com/problems/unique-paths-ii/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "247",
    name: "Jump Game II",
    description: "",
    link: "https://leetcode.com/problems/jump-game-ii/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "248",
    name: "Gas Station",
    description: "",
    link: "https://leetcode.com/problems/gas-station/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
];
