import { DSASheetProblemType } from "../../utils/dsa-sheet-type";

export const GREEDY: DSASheetProblemType[] = [
  {
    id: "greedy-1",
    name: "Jump Game",
    description: "",
    link: "https://leetcode.com/problems/jump-game/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "greedy-2",
    name: "Jump Game II",
    description: "",
    link: "https://leetcode.com/problems/jump-game-ii/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "greedy-3",
    name: "Task Scheduler",
    description: "",
    link: "https://leetcode.com/problems/task-scheduler/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "greedy-4",
    name: "Minimum Number of Arrows to Burst Balloons",
    description: "",
    link: "https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "greedy-5",
    name: "Jump Game",
    description: "",
    link: "https://leetcode.com/problems/jump-game/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "greedy-6",
    name: "Edit Distance",
    description: "",
    link: "https://leetcode.com/problems/edit-distance/",
    guideLink: "",
    difficultyLevel: "Hard",
  },
  {
    id: "greedy-7",
    name: "Palindromic Substrings",
    description: "",
    link: "https://leetcode.com/problems/palindromic-substrings/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "greedy-8",
    name: "Wildcard Matching",
    description: "",
    link: "https://leetcode.com/problems/wildcard-matching/",
    guideLink: "",
    difficultyLevel: "Hard",
  },
  {
    id: "greedy-9",
    name: "Buy and Sell Stock with Cooldown",
    description: "",
    link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "greedy-10",
    name: "Maximum Product Subarray",
    description: "",
    link: "https://leetcode.com/problems/maximum-product-subarray/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "greedy-11",
    name: "Minimum Path Sum",
    description: "",
    link: "https://leetcode.com/problems/minimum-path-sum/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "greedy-12",
    name: "Unique Paths II",
    description: "",
    link: "https://leetcode.com/problems/unique-paths-ii/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "greedy-13",
    name: "Jump Game II",
    description: "",
    link: "https://leetcode.com/problems/jump-game-ii/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "greedy-14",
    name: "Gas Station",
    description: "",
    link: "https://leetcode.com/problems/gas-station/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
];
