import { DSASheetProblemType } from "../../utils/dsa-sheet-type";

export const HEAP_AND_PRIORITY_QUEUE: DSASheetProblemType[] = [
  {
    id: "1",
    name: "Kth Largest Element in a Stream",
    description: "Find the kth largest element in a stream.",
    link: "https://leetcode.com/problems/kth-largest-element-in-a-stream/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
  {
    id: "2",
    name: "K Closest Points to Origin",
    description: "Find the k closest points to the origin.",
    link: "https://leetcode.com/problems/k-closest-points-to-origin/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "3",
    name: "Task Scheduler",
    description: "Schedule tasks with a cooldown period.",
    link: "https://leetcode.com/problems/task-scheduler/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "4",
    name: "Find Median from Data Stream",
    description: "Find the median from a data stream.",
    link: "https://leetcode.com/problems/find-median-from-data-stream/",
    guideLink: "",
    difficultyLevel: "Hard",
  },
  {
    id: "5",
    name: "Top K Frequent Words",
    description: "Find the top k frequent words in a list.",
    link: "https://leetcode.com/problems/top-k-frequent-words/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "6",
    name: "Find K Pairs with Smallest Sums",
    description: "Find k pairs with the smallest sums.",
    link: "https://leetcode.com/problems/find-k-pairs-with-smallest-sums/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "7",
    name: "Kth Largest Element in an Array",
    description: "Find the kth largest element in an array.",
    link: "https://leetcode.com/problems/kth-largest-element-in-an-array/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "8",
    name: "K Closest Points to Origin",
    description: "Find the k closest points to the origin.",
    link: "https://leetcode.com/problems/k-closest-points-to-origin/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "9",
    name: "Merge K Sorted Lists",
    description:
      "Merge k sorted linked lists and return it as one sorted list.",
    link: "https://leetcode.com/problems/merge-k-sorted-lists/",
    guideLink: "",
    difficultyLevel: "Hard",
  },
  {
    id: "10",
    name: "Top K Frequent Elements",
    description: "Find the top k frequent elements in an array.",
    link: "https://leetcode.com/problems/top-k-frequent-elements/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "11",
    name: "Kth Largest Element in an Array",
    description: "Find the kth largest element in an array.",
    link: "https://leetcode.com/problems/kth-largest-element-in-an-array/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "12",
    name: "Find Median from Data Stream",
    description: "Find the median from a data stream.",
    link: "https://leetcode.com/problems/find-median-from-data-stream/",
    guideLink: "",
    difficultyLevel: "Hard",
  },
  {
    id: "13",
    name: "K Closest Points to Origin",
    description: "Find the k closest points to the origin.",
    link: "https://leetcode.com/problems/k-closest-points-to-origin/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "14",
    name: "Find K Pairs with Smallest Sums",
    description: "Find k pairs with the smallest sums.",
    link: "https://leetcode.com/problems/find-k-pairs-with-smallest-sums/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "15",
    name: "Merge K Sorted Lists",
    description:
      "Merge k sorted linked lists and return it as one sorted list.",
    link: "https://leetcode.com/problems/merge-k-sorted-lists/",
    guideLink: "",
    difficultyLevel: "Hard",
  },
  {
    id: "16",
    name: "Sliding Window Maximum",
    description: "Find the maximum value in each sliding window of size k.",
    link: "https://leetcode.com/problems/sliding-window-maximum/",
    guideLink: "",
    difficultyLevel: "Hard",
  },
];
