import { DSASheetProblemType } from "../../utils/dsa-sheet-type";

export const MATH_AND_GEOMETRY: DSASheetProblemType[] = [
  {
    id: "103",
    name: "Happy Number",
    description: "",
    link: "https://leetcode.com/problems/happy-number/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
  {
    id: "104",
    name: "Sieve of Eratosthenes",
    description: "",
    link: "https://leetcode.com/problems/count-primes/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "60",
    name: "Integer to Roman",
    description: "",
    link: "https://leetcode.com/problems/integer-to-roman/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "58",
    name: "Single Number",
    description: "",
    link: "https://leetcode.com/problems/single-number/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
  {
    id: "101",
    name: "Sum of Two Integers",
    description: "",
    link: "https://leetcode.com/problems/sum-of-two-integers/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "151",
    name: "Spiral Matrix",
    description: "",
    link: "https://leetcode.com/problems/spiral-matrix/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "152",
    name: "Power of Two",
    description: "",
    link: "https://leetcode.com/problems/power-of-two/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
  {
    id: "199",
    name: "Valid Number",
    description: "",
    link: "https://leetcode.com/problems/valid-number/",
    guideLink: "",
    difficultyLevel: "Hard",
  },
  {
    id: "200",
    name: "Angle Between Hands of a Clock",
    description: "",
    link: "https://leetcode.com/problems/angle-between-hands-of-a-clock/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "250",
    name: "Count Primes",
    description: "",
    link: "https://leetcode.com/problems/count-primes/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "251",
    name: "Happy Number",
    description: "",
    link: "https://leetcode.com/problems/happy-number/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
];
