import { DSASheetProblemType } from "../../utils/dsa-sheet-type";

export const TWO_POINTER: DSASheetProblemType[] = [
  {
    id: "two-pointer-1",
    name: "Valid Palindrome",
    description: "Check if a string is a valid palindrome.",
    link: "https://leetcode.com/problems/valid-palindrome/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
  {
    id: "two-pointer-2",
    name: "Two Sum II - Input Array Is Sorted",
    description:
      "Find two numbers that add up to a specific target in a sorted array.",
    link: "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "two-pointer-3",
    name: "3Sum",
    description: "Find three numbers that add up to a specific target.",
    link: "https://leetcode.com/problems/3sum/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "two-pointer-4",
    name: "Container With Most Water",
    description:
      "Find two lines that together with the x-axis form a container that holds the most water.",
    link: "https://leetcode.com/problems/container-with-most-water/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "two-pointer-5",
    name: "Trapping Rain Water",
    description: "Calculate how much water it can trap after raining.",
    link: "https://leetcode.com/problems/trapping-rain-water/",
    guideLink: "",
    difficultyLevel: "Hard",
  },
  {
    id: "two-pointer-6",
    name: "Remove Duplicates from Sorted Array",
    description: "Remove duplicates in-place from a sorted array.",
    link: "https://leetcode.com/problems/remove-duplicates-from-sorted-array/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
  {
    id: "two-pointer-7",
    name: "Move Zeroes",
    description:
      "Move all zeroes to the end of the array while maintaining the relative order of the non-zero elements.",
    link: "https://leetcode.com/problems/move-zeroes/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
  {
    id: "two-pointer-8",
    name: "Merge Sorted Array",
    description: "Merge two sorted arrays into one sorted array.",
    link: "https://leetcode.com/problems/merge-sorted-array/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
  {
    id: "two-pointer-9",
    name: "Reverse String",
    description: "Reverse a string.",
    link: "https://leetcode.com/problems/reverse-string/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
  {
    id: "two-pointer-10",
    name: "Remove Element",
    description:
      "Remove all instances of a value in-place and return the new length.",
    link: "https://leetcode.com/problems/remove-element/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
  {
    id: "two-pointer-11",
    name: "Find the Difference of Two Arrays",
    description: "Find the difference between two arrays.",
    link: "https://leetcode.com/problems/find-the-difference-of-two-arrays/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
  {
    id: "two-pointer-12",
    name: "Reverse Vowels of a String",
    description: "Reverse the vowels of a string.",
    link: "https://leetcode.com/problems/reverse-vowels-of-a-string/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
  {
    id: "two-pointer-13",
    name: "Partition Labels",
    description:
      "Partition a string into as many parts as possible so that each letter appears in at most one part.",
    link: "https://leetcode.com/problems/partition-labels/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "two-pointer-14",
    name: "3Sum Closest",
    description:
      "Find three integers in an array such that the sum is closest to a given number.",
    link: "https://leetcode.com/problems/3sum-closest/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "two-pointer-15",
    name: "Minimum Size Subarray Sum",
    description:
      "Find the minimal length of a contiguous subarray of which the sum is greater than or equal to a given number.",
    link: "https://leetcode.com/problems/minimum-size-subarray-sum/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "two-pointer-16",
    name: "Container With Most Water",
    description:
      "Find two lines that together with the x-axis form a container that holds the most water.",
    link: "https://leetcode.com/problems/container-with-most-water/",
    guideLink: "",
    difficultyLevel: "Medium",
  },
  {
    id: "two-pointer-17",
    name: "Valid Palindrome",
    description: "Check if a string is a valid palindrome.",
    link: "https://leetcode.com/problems/valid-palindrome/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
  {
    id: "two-pointer-18",
    name: "Remove Element",
    description:
      "Remove all instances of a value in-place and return the new length.",
    link: "https://leetcode.com/problems/remove-element/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
  {
    id: "two-pointer-19",
    name: "Find the Difference of Two Arrays",
    description: "Find the difference between two arrays.",
    link: "https://leetcode.com/problems/find-the-difference-of-two-arrays/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
  {
    id: "two-pointer-20",
    name: "Reverse String",
    description: "Reverse a string.",
    link: "https://leetcode.com/problems/reverse-string/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
  {
    id: "two-pointer-21",
    name: "Reverse Vowels of a String",
    description: "Reverse the vowels of a string.",
    link: "https://leetcode.com/problems/reverse-vowels-of-a-string/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
  {
    id: "two-pointer-22",
    name: "Remove Duplicates from Sorted Array",
    description: "Remove duplicates in-place from a sorted array.",
    link: "https://leetcode.com/problems/remove-duplicates-from-sorted-array/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
  {
    id: "two-pointer-23",
    name: "Move Zeroes",
    description:
      "Move all zeroes to the end of the array while maintaining the relative order of the non-zero elements.",
    link: "https://leetcode.com/problems/move-zeroes/",
    guideLink: "",
    difficultyLevel: "Easy",
  },
];
